# -*- coding: utf-8 -*-
"""
Marex Solutions - Yahoo Finance Stock Screener Web App

Dark Streamlit web application reading the Excel file generated by main.py:
- Stock Screener.xlsx
- extraction YF sheet

This version uses the Marex / Marex Solutions palette and mirrors the previous
desktop layout: header, toolbar, filters, table on the left, ticker details on
the right. KPI cards above the table were removed.
"""

from __future__ import annotations

import html
import math
import os
import subprocess
import sys
from pathlib import Path
from typing import Any, Optional

import numpy as np
import pandas as pd
import plotly.express as px
import streamlit as st

try:
    from st_aggrid import AgGrid, DataReturnMode, GridOptionsBuilder, GridUpdateMode, JsCode

    AGGRID_AVAILABLE = True
except Exception:
    JsCode = None
    AGGRID_AVAILABLE = False


APP_DIR = Path(__file__).resolve().parent
DEFAULT_EXCEL_NAME = "Stock Screener.xlsx"
DEFAULT_OUTPUT_SHEET = "extraction YF"
DEFAULT_MAIN_SCRIPT = "main.py"

# Marex / Marex Solutions palette.
MAREX_BLUE_DARKEST = "#0E0D24"
MAREX_BLUE_DARKER = "#121230"
MAREX_BLUE_DARK = "#1C1B4A"
MAREX_SOLUTIONS_VIOLET = "#843FDC"
MAREX_SOLUTIONS_VIOLET_DARKER = "#4D2480"
MAREX_SOLUTIONS_VIOLET_DARKEST = "#1F0F33"
MAREX_SOLUTIONS_VIOLET_50 = "#CF9EED"
MAREX_SOLUTIONS_VIOLET_20 = "#ECD9F8"
MAREX_GREY_LIGHT = "#DADAE7"
MAREX_GREY_LIGHT_30 = "#F5F5F8"
MAREX_GREY_MID = "#505068"
MAREX_GREY_MID_70 = "#858596"
MAREX_GREEN = "#2D8D79"
MAREX_CORAL = "#FF846A"
MAREX_ROW_ALT = "#171735"

PREFERRED_COLUMNS = [
    "ticker",
    "company_name",
    "company_description",
    "close_price",
    "YTD return",
    "1 week return",
    "Current target",
    "Upgrades / downgrades",
    "Analyst recommendations",
    "sector",
    "country",
    "next_earnings_date",
    "dividend_yield",
    "market_cap",
    "currency",
    "price_earnings_ratio",
    "variance_swap_target_dte",
    "variance_swap_selected_dte",
    "variance_swap_selected_expiration",
    "variance_swap_strike_variance",
    "variance_swap_strike_vol",
    "variance_swap_strike_vol_pct",
    "variance_swap_forward_price",
    "variance_swap_k0",
    "variance_swap_options_used",
    "extraction_datetime",
]

# Columns kept for ticker details but hidden from the main table.
TABLE_HIDDEN_COLUMNS = {
    "company_description",
    "Current target",
    "Upgrades / downgrades",
    "Analyst recommendations",
    "market_cap",
    "variance_swap_target_dte",
    "variance_swap_selected_dte",
    "variance_swap_selected_expiration",
    "variance_swap_forward_price",
    "variance_swap_options_used",
    "extraction_datetime",
}

NUMERIC_COLUMNS = {
    "close_price",
    "YTD return",
    "1 week return",
    "Current target",
    "dividend_yield",
    "market_cap",
    "price_earnings_ratio",
    "variance_swap_target_dte",
    "variance_swap_selected_dte",
    "variance_swap_strike_variance",
    "variance_swap_strike_vol",
    "variance_swap_strike_vol_pct",
    "variance_swap_forward_price",
    "variance_swap_k0",
    "variance_swap_options_used",
}

DATE_COLUMNS = {
    "next_earnings_date",
    "variance_swap_selected_expiration",
    "extraction_datetime",
}

DISPLAY_NAMES = {
    "ticker": "Ticker",
    "company_name": "Company",
    "company_description": "Description",
    "close_price": "Close",
    "YTD return": "YTD return",
    "1 week return": "1W return",
    "Current target": "Current target",
    "Upgrades / downgrades": "Upgrades / downgrades",
    "Analyst recommendations": "Analyst recommendations",
    "sector": "Sector",
    "country": "Country",
    "next_earnings_date": "Next earnings",
    "dividend_yield": "Div. yield",
    "market_cap": "Market cap",
    "currency": "Currency",
    "price_earnings_ratio": "P/E",
    "variance_swap_target_dte": "Target DTE",
    "variance_swap_selected_dte": "Selected DTE",
    "variance_swap_selected_expiration": "Expiry",
    "variance_swap_strike_variance": "Var strike",
    "variance_swap_strike_vol": "Vol strike",
    "variance_swap_strike_vol_pct": "Vol strike %",
    "variance_swap_forward_price": "Forward",
    "variance_swap_k0": "K0",
    "variance_swap_options_used": "Options used",
    "extraction_datetime": "Extracted at",
}

DETAIL_FIELDS = [
    "ticker",
    "company_name",
    "sector",
    "country",
    "currency",
    "close_price",
    "YTD return",
    "1 week return",
    "Current target",
    "market_cap",
    "price_earnings_ratio",
    "dividend_yield",
    "next_earnings_date",
    "Upgrades / downgrades",
    "Analyst recommendations",
    "variance_swap_target_dte",
    "variance_swap_selected_dte",
    "variance_swap_selected_expiration",
    "variance_swap_strike_vol_pct",
    "variance_swap_strike_variance",
    "variance_swap_forward_price",
    "variance_swap_k0",
    "variance_swap_options_used",
    "extraction_datetime",
]

TABLE_COLUMNS = [col for col in PREFERRED_COLUMNS if col not in TABLE_HIDDEN_COLUMNS]
FILTER_STATE_KEYS = [
    "filter_search",
    "filter_sector",
    "filter_country",
    "filter_currency",
    "filter_market_cap_bucket",
    "filter_var_vol_bucket",
    # Legacy keys from the old min/max volatility inputs. Kept here so Reset filters
    # clears old Streamlit session state if the app was already open in the browser.
    "filter_var_vol_min",
    "filter_var_vol_max",
    "filter_pe_min",
    "filter_pe_max",
    "filter_ytd_min",
    "filter_ytd_max",
    "filter_1w_min",
    "filter_1w_max",
]

MARKET_CAP_BUCKETS = {
    "All": (None, None),
    "Mega Cap > 200 milliards": (200_000_000_000, None),
    "Large Cap 10-200 milliards": (10_000_000_000, 200_000_000_000),
    "Mid Cap 2-10 milliards": (2_000_000_000, 10_000_000_000),
    "Small Cap < 2 milliards": (None, 2_000_000_000),
}

VOL_STRIKE_BUCKETS = {
    "All": (None, None),
    "Very High Vol > 60%": (60.0, None),
    "High Vol 40%-60%": (40.0, 60.0),
    "Mid Vol 20%-40%": (20.0, 40.0),
    "Low Vol < 20%": (None, 20.0),
}


# -----------------------------------------------------------------------------
# Generic helpers
# -----------------------------------------------------------------------------

def is_null(value: Any) -> bool:
    if value is None:
        return True
    try:
        return bool(pd.isna(value))
    except Exception:
        return False


def safe_float(value: Any) -> Optional[float]:
    if is_null(value):
        return None
    if isinstance(value, (int, float, np.integer, np.floating)):
        val = float(value)
        return val if math.isfinite(val) else None
    if isinstance(value, str):
        cleaned = (
            value.strip()
            .replace("%", "")
            .replace(",", "")
            .replace(" ", "")
            .replace("\u00a0", "")
        )
        if not cleaned:
            return None
        try:
            val = float(cleaned)
            return val if math.isfinite(val) else None
        except ValueError:
            return None
    return None


def normalize_text(value: Any) -> str:
    if is_null(value):
        return ""
    return str(value).strip()


def escape(value: Any) -> str:
    return html.escape(normalize_text(value))


def human_number(value: Any, decimals: int = 1) -> str:
    val = safe_float(value)
    if val is None:
        return ""
    abs_val = abs(val)
    if abs_val >= 1_000_000_000_000:
        return f"{val / 1_000_000_000_000:,.{decimals}f}T"
    if abs_val >= 1_000_000_000:
        return f"{val / 1_000_000_000:,.{decimals}f}B"
    if abs_val >= 1_000_000:
        return f"{val / 1_000_000:,.{decimals}f}M"
    if abs_val >= 1_000:
        return f"{val / 1_000:,.{decimals}f}K"
    return f"{val:,.{decimals}f}"


def format_date(value: Any) -> str:
    if is_null(value):
        return ""
    try:
        ts = pd.to_datetime(value, errors="coerce")
    except Exception:
        return str(value)
    if pd.isna(ts):
        return str(value)
    if getattr(ts, "tzinfo", None) is not None:
        try:
            ts = ts.tz_convert(None)
        except Exception:
            ts = ts.tz_localize(None)
    if getattr(ts, "hour", 0) == 0 and getattr(ts, "minute", 0) == 0 and getattr(ts, "second", 0) == 0:
        return ts.strftime("%Y-%m-%d")
    return ts.strftime("%Y-%m-%d %H:%M")


def format_percent(value: Any, column: str) -> str:
    val = safe_float(value)
    if val is None:
        return ""
    if column in {"YTD return", "1 week return"}:
        # Stock returns are stored as decimals in Excel: 0.05 = 5%.
        val *= 100
    elif column in {"dividend_yield", "variance_swap_strike_vol"}:
        if abs(val) <= 2:
            val *= 100
    return f"{val:,.2f}%"


def format_cell_value(column: str, value: Any) -> str:
    if is_null(value):
        return ""
    if column in DATE_COLUMNS or "date" in column.lower() or "expiration" in column.lower():
        return format_date(value)
    if column == "market_cap":
        return human_number(value)
    if column in {"dividend_yield", "YTD return", "1 week return", "variance_swap_strike_vol", "variance_swap_strike_vol_pct"}:
        return format_percent(value, column)
    if column in NUMERIC_COLUMNS:
        val = safe_float(value)
        if val is None:
            return ""
        if abs(val) >= 1000:
            return f"{val:,.0f}"
        return f"{val:,.2f}"
    return str(value)


def reorder_columns(df: pd.DataFrame) -> pd.DataFrame:
    existing = [col for col in PREFERRED_COLUMNS if col in df.columns]
    remaining = [col for col in df.columns if col not in existing]
    return df[existing + remaining]


def clean_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df.columns = [str(c).strip() for c in df.columns]

    for col in df.columns:
        if col in NUMERIC_COLUMNS:
            df[col] = pd.to_numeric(df[col], errors="coerce")
        elif col in DATE_COLUMNS or "date" in col.lower() or "expiration" in col.lower():
            df[col] = pd.to_datetime(df[col], errors="coerce")
            try:
                if getattr(df[col].dt, "tz", None) is not None:
                    df[col] = df[col].dt.tz_localize(None)
            except Exception:
                pass

    return reorder_columns(df)


def get_secret_or_env(name: str, default: Any = None) -> Any:
    """Read from Streamlit secrets first, then environment variables."""
    for key in (name, name.lower(), name.upper()):
        try:
            if key in st.secrets:
                return st.secrets[key]
        except Exception:
            pass
        if key in os.environ:
            return os.environ[key]
    return default


def to_bool(value: Any, default: bool = False) -> bool:
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"1", "true", "yes", "y", "on"}


def get_excel_path() -> Path:
    configured = get_secret_or_env("EXCEL_PATH", None)
    if configured:
        return Path(str(configured)).expanduser()
    return APP_DIR / DEFAULT_EXCEL_NAME


def get_sheet_name() -> str:
    return str(get_secret_or_env("OUTPUT_SHEET", DEFAULT_OUTPUT_SHEET))


def get_file_signature(path: Path) -> tuple[str, int, int]:
    if not path.exists():
        return (str(path), 0, 0)
    stat = path.stat()
    return (str(path), stat.st_mtime_ns, stat.st_size)


@st.cache_data(ttl=60, show_spinner=False)
def read_dashboard_excel(path_str: str, sheet_name: str, mtime_ns: int, size: int) -> pd.DataFrame:
    path = Path(path_str)
    if not path.exists():
        raise FileNotFoundError(f"Excel file not found: {path}")
    df = pd.read_excel(path, sheet_name=sheet_name)
    return clean_dataframe(df)


def build_search_index(df: pd.DataFrame) -> pd.Series:
    if df.empty:
        return pd.Series(dtype=str)
    candidate_cols = [
        "ticker",
        "company_name",
        "sector",
        "country",
        "currency",
        "company_description",
        "Upgrades / downgrades",
        "Analyst recommendations",
    ]
    cols = [col for col in candidate_cols if col in df.columns]
    if not cols:
        return pd.Series([""] * len(df), index=df.index)
    return df[cols].fillna("").astype(str).agg(" ".join, axis=1).str.lower()


def parse_float_input(value: Any) -> Optional[float]:
    if value is None or value == "":
        return None
    try:
        return float(str(value).replace(",", "."))
    except ValueError:
        return None


def apply_numeric_range(df: pd.DataFrame, column: str, min_value: Optional[float], max_value: Optional[float]) -> pd.DataFrame:
    if column not in df.columns or (min_value is None and max_value is None):
        return df
    values = pd.to_numeric(df[column], errors="coerce")
    mask = pd.Series(True, index=df.index)
    if min_value is not None:
        mask &= values >= min_value
    if max_value is not None:
        mask &= values <= max_value
    return df[mask]


def apply_market_cap_bucket(df: pd.DataFrame, bucket: str) -> pd.DataFrame:
    """
    Filtre par bucket de capitalisation boursiere.
    Les seuils sont appliques directement sur la colonne market_cap renvoyee par Yahoo Finance.
    """
    if not bucket or bucket == "All" or "market_cap" not in df.columns:
        return df

    min_value, max_value = MARKET_CAP_BUCKETS.get(bucket, (None, None))
    values = pd.to_numeric(df["market_cap"], errors="coerce")
    mask = pd.Series(True, index=df.index)

    if min_value is not None:
        mask &= values > min_value if bucket.startswith("Mega Cap") else values >= min_value
    if max_value is not None:
        mask &= values < max_value if bucket.startswith("Small Cap") else values <= max_value

    return df[mask]


def apply_vol_strike_bucket(df: pd.DataFrame, bucket: str) -> pd.DataFrame:
    """
    Filtre par bucket de volatilite variance swap, en pourcentage.
    La colonne variance_swap_strike_vol_pct est deja exprimee en pourcentage.
    """
    if not bucket or bucket == "All" or "variance_swap_strike_vol_pct" not in df.columns:
        return df

    min_value, max_value = VOL_STRIKE_BUCKETS.get(bucket, (None, None))
    values = pd.to_numeric(df["variance_swap_strike_vol_pct"], errors="coerce")
    mask = pd.Series(True, index=df.index)

    if bucket == "Very High Vol > 60%":
        mask &= values > min_value
    elif bucket == "High Vol 40%-60%":
        mask &= (values >= min_value) & (values <= max_value)
    elif bucket == "Mid Vol 20%-40%":
        mask &= (values >= min_value) & (values < max_value)
    elif bucket == "Low Vol < 20%":
        mask &= values < max_value

    return df[mask]


def filter_dataframe(
    df: pd.DataFrame,
    search_text: str,
    sector: str,
    country: str,
    currency: str,
    market_cap_bucket: str,
    var_vol_bucket: str,
    pe_min: Optional[float],
    pe_max: Optional[float],
    ytd_min_pct: Optional[float],
    ytd_max_pct: Optional[float],
    one_week_min_pct: Optional[float],
    one_week_max_pct: Optional[float],
) -> pd.DataFrame:
    filtered = df.copy()

    search_text = (search_text or "").strip().lower()
    if search_text:
        index = build_search_index(filtered)
        filtered = filtered[index.str.contains(search_text, na=False, regex=False)]

    if sector and sector != "All" and "sector" in filtered.columns:
        filtered = filtered[filtered["sector"].fillna("").astype(str).str.strip() == sector]

    if country and country != "All" and "country" in filtered.columns:
        filtered = filtered[filtered["country"].fillna("").astype(str).str.strip() == country]

    if currency and currency != "All" and "currency" in filtered.columns:
        filtered = filtered[filtered["currency"].fillna("").astype(str).str.strip() == currency]

    filtered = apply_market_cap_bucket(filtered, market_cap_bucket)
    filtered = apply_vol_strike_bucket(filtered, var_vol_bucket)
    filtered = apply_numeric_range(filtered, "price_earnings_ratio", pe_min, pe_max)

    # Returns are stored as decimals in Excel. User inputs are percentages.
    filtered = apply_numeric_range(
        filtered,
        "YTD return",
        ytd_min_pct / 100 if ytd_min_pct is not None else None,
        ytd_max_pct / 100 if ytd_max_pct is not None else None,
    )
    filtered = apply_numeric_range(
        filtered,
        "1 week return",
        one_week_min_pct / 100 if one_week_min_pct is not None else None,
        one_week_max_pct / 100 if one_week_max_pct is not None else None,
    )

    return filtered



def prepare_table_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    table_cols = [col for col in TABLE_COLUMNS if col in df.columns]
    display = df[table_cols].copy()

    # Convert return columns from decimals to percentages for display in the grid.
    for col in ["YTD return", "1 week return"]:
        if col in display.columns:
            display[col] = pd.to_numeric(display[col], errors="coerce") * 100

    if "dividend_yield" in display.columns:
        div = pd.to_numeric(display["dividend_yield"], errors="coerce")
        display["dividend_yield"] = div.where(div.abs() > 2, div * 100)

    if "variance_swap_strike_vol" in display.columns:
        vol = pd.to_numeric(display["variance_swap_strike_vol"], errors="coerce")
        display["variance_swap_strike_vol"] = vol.where(vol.abs() > 2, vol * 100)

    for col in display.columns:
        if col in DATE_COLUMNS or "date" in col.lower() or "expiration" in col.lower():
            display[col] = display[col].apply(format_date)

    return display


def build_column_config(df: pd.DataFrame) -> dict[str, Any]:
    config: dict[str, Any] = {}

    for col in df.columns:
        label = DISPLAY_NAMES.get(col, col)
        if col in {"YTD return", "1 week return", "dividend_yield", "variance_swap_strike_vol", "variance_swap_strike_vol_pct"}:
            config[col] = st.column_config.NumberColumn(label, format="%.2f%%")
        elif col == "market_cap":
            config[col] = st.column_config.NumberColumn(label, format="%.0f")
        elif col in NUMERIC_COLUMNS:
            config[col] = st.column_config.NumberColumn(label, format="%.2f")
        else:
            config[col] = st.column_config.TextColumn(label)

    return config


def get_selected_row_by_ticker(ticker: str, filtered_df: pd.DataFrame) -> Optional[pd.Series]:
    if not ticker or "ticker" not in filtered_df.columns:
        return None
    matches = filtered_df[filtered_df["ticker"].astype(str) == str(ticker)]
    if matches.empty:
        return None
    return matches.iloc[0]


def fallback_selected_row(filtered_df: pd.DataFrame) -> Optional[pd.Series]:
    if filtered_df.empty:
        return None
    saved_ticker = st.session_state.get("selected_ticker")
    if saved_ticker:
        matched = get_selected_row_by_ticker(str(saved_ticker), filtered_df)
        if matched is not None:
            return matched
    return filtered_df.iloc[0]


def reset_filters() -> None:
    for key in FILTER_STATE_KEYS:
        st.session_state.pop(key, None)


def run_extraction_script() -> tuple[int, str, str]:
    script_path = APP_DIR / DEFAULT_MAIN_SCRIPT
    if not script_path.exists():
        return 1, "", f"{DEFAULT_MAIN_SCRIPT} not found in {APP_DIR}"

    timeout_seconds = int(get_secret_or_env("REFRESH_TIMEOUT_SECONDS", 60 * 60))
    cmd = [sys.executable, str(script_path)]

    result = subprocess.run(
        cmd,
        cwd=str(APP_DIR),
        capture_output=True,
        text=True,
        timeout=timeout_seconds,
        check=False,
    )
    return result.returncode, result.stdout, result.stderr


def require_password_if_configured() -> None:
    password = get_secret_or_env("APP_PASSWORD", None)
    if not password:
        return

    if st.session_state.get("authenticated"):
        return

    st.title("Marex Solutions - Stock Screener")
    st.caption("Access protected")
    entered = st.text_input("Password", type="password")
    if st.button("Log in"):
        if entered == str(password):
            st.session_state["authenticated"] = True
            st.rerun()
        else:
            st.error("Invalid password")
    st.stop()


# -----------------------------------------------------------------------------
# Rendering helpers
# -----------------------------------------------------------------------------

def inject_css() -> None:
    st.markdown(
        f"""
        <style>
            :root {{
                --marex-blue-darkest: {MAREX_BLUE_DARKEST};
                --marex-blue-darker: {MAREX_BLUE_DARKER};
                --marex-blue-dark: {MAREX_BLUE_DARK};
                --marex-violet: {MAREX_SOLUTIONS_VIOLET};
                --marex-violet-darker: {MAREX_SOLUTIONS_VIOLET_DARKER};
                --marex-violet-50: {MAREX_SOLUTIONS_VIOLET_50};
                --marex-grey-light: {MAREX_GREY_LIGHT};
                --marex-grey-mid: {MAREX_GREY_MID};
                --marex-grey-mid-70: {MAREX_GREY_MID_70};
            }}
            html, body, [data-testid='stAppViewContainer'], .stApp {{
                background: {MAREX_BLUE_DARKEST} !important;
                color: {MAREX_GREY_LIGHT} !important;
            }}
            [data-testid='stHeader'] {{
                background: rgba(14, 13, 36, 0.96) !important;
                border-bottom: 1px solid {MAREX_BLUE_DARK};
            }}
            [data-testid='stToolbar'] {{
                color: {MAREX_GREY_LIGHT} !important;
            }}
            [data-testid='stSidebar'] {{
                background: {MAREX_BLUE_DARKER} !important;
                color: {MAREX_GREY_LIGHT} !important;
                border-right: 1px solid {MAREX_BLUE_DARK};
            }}
            .block-container {{
                /* Keep enough space below Streamlit's fixed top bar so the
                   Marex title is never clipped at the top of the page. */
                padding-top: 3.0rem !important;
                padding-bottom: 2rem !important;
                max-width: 100% !important;
            }}
            h1, h2, h3, h4, h5, h6, p, span, label, div {{
                color: {MAREX_GREY_LIGHT};
            }}
            .marex-header {{
                background: linear-gradient(135deg, {MAREX_BLUE_DARKER}, {MAREX_BLUE_DARK});
                border: 1px solid {MAREX_BLUE_DARK};
                border-radius: 18px;
                padding: 30px 24px 22px 24px;
                margin-top: 8px;
                margin-bottom: 12px;
                box-shadow: 0 18px 45px rgba(0, 0, 0, 0.24);
                overflow: visible !important;
            }}
            .marex-title {{
                display: block;
                overflow: visible !important;
                font-size: 30px;
                font-weight: 850;
                letter-spacing: 2px;
                color: #FFFFFF !important;
                line-height: 1.38;
                margin: 0 0 2px 0;
                padding-top: 4px;
            }}
            .marex-subtitle {{
                color: {MAREX_SOLUTIONS_VIOLET_50} !important;
                font-size: 14px;
                margin-top: 5px;
            }}
            .source-line {{
                display: flex;
                flex-wrap: wrap;
                gap: 8px;
                margin-top: 12px;
                align-items: center;
            }}
            .status-chip, .source-chip, .row-count-chip {{
                display: inline-flex;
                align-items: center;
                border-radius: 999px;
                padding: 6px 10px;
                font-size: 12px;
                font-weight: 700;
                letter-spacing: .2px;
            }}
            .status-chip {{
                background: {MAREX_GREEN};
                color: #FFFFFF !important;
                border: 1px solid {MAREX_GREEN};
            }}
            .source-chip, .row-count-chip {{
                background: {MAREX_BLUE_DARK};
                color: {MAREX_GREY_LIGHT} !important;
                border: 1px solid {MAREX_GREY_MID};
            }}
            .section-title {{
                color: #FFFFFF !important;
                font-size: 18px;
                font-weight: 800;
                margin: 2px 0 10px 0;
            }}
            .panel-card, .filters-card, .right-card {{
                background: {MAREX_BLUE_DARKER};
                border: 1px solid {MAREX_BLUE_DARK};
                border-radius: 16px;
                padding: 14px;
                box-shadow: 0 14px 35px rgba(0, 0, 0, 0.18);
            }}
            .filters-title-row, .panel-title-row {{
                display: flex;
                align-items: center;
                justify-content: space-between;
                gap: 12px;
                margin-bottom: 8px;
            }}
            .muted-text {{
                color: {MAREX_GREY_MID_70} !important;
                font-size: 13px;
            }}
            .stTextInput label, .stSelectbox label, .stFileUploader label {{
                color: {MAREX_GREY_LIGHT} !important;
                font-weight: 700 !important;
            }}
            .stTextInput input {{
                background: {MAREX_BLUE_DARK} !important;
                color: #FFFFFF !important;
                border: 1px solid {MAREX_GREY_MID} !important;
                border-radius: 9px !important;
            }}
            .stTextInput input::placeholder {{
                color: {MAREX_GREY_MID_70} !important;
                opacity: 1 !important;
            }}
            .stTextInput input:focus {{
                border-color: {MAREX_SOLUTIONS_VIOLET} !important;
                box-shadow: 0 0 0 1px {MAREX_SOLUTIONS_VIOLET} !important;
            }}
            div[data-baseweb='select'] > div {{
                background: {MAREX_BLUE_DARK} !important;
                color: #FFFFFF !important;
                border: 1px solid {MAREX_GREY_MID} !important;
                border-radius: 9px !important;
            }}
            div[data-baseweb='select'] > div * {{
                color: #FFFFFF !important;
                fill: #FFFFFF !important;
            }}
            /* Dropdown option list: light background + dark font for readability. */
            div[data-baseweb='popover'], div[data-baseweb='menu'], div[role='listbox'] {{
                background: {MAREX_GREY_LIGHT_30} !important;
                color: {MAREX_BLUE_DARKEST} !important;
                border: 1px solid {MAREX_SOLUTIONS_VIOLET_50} !important;
            }}
            div[data-baseweb='popover'] *, div[data-baseweb='menu'] *, div[role='listbox'] * {{
                color: {MAREX_BLUE_DARKEST} !important;
            }}
            div[role='option'], div[role='option'] * {{
                background: {MAREX_GREY_LIGHT_30} !important;
                color: {MAREX_BLUE_DARKEST} !important;
            }}
            div[role='option']:hover, div[role='option'][aria-selected='true'] {{
                background: {MAREX_SOLUTIONS_VIOLET_20} !important;
                color: {MAREX_BLUE_DARKEST} !important;
            }}
            .stButton > button, .stDownloadButton > button {{
                background: {MAREX_SOLUTIONS_VIOLET} !important;
                color: #FFFFFF !important;
                border: 1px solid {MAREX_SOLUTIONS_VIOLET} !important;
                border-radius: 10px !important;
                font-weight: 800 !important;
                min-height: 38px;
            }}
            .stButton > button:hover, .stDownloadButton > button:hover {{
                background: {MAREX_SOLUTIONS_VIOLET_50} !important;
                color: {MAREX_BLUE_DARKEST} !important;
                border-color: {MAREX_SOLUTIONS_VIOLET_50} !important;
            }}
            .stExpander {{
                background: {MAREX_BLUE_DARKER} !important;
                border: 1px solid {MAREX_BLUE_DARK} !important;
                border-radius: 12px !important;
            }}
            .right-card {{
                min-height: 650px;
            }}
            .detail-title {{
                color: #FFFFFF !important;
                font-size: 26px;
                font-weight: 850;
                line-height: 1.05;
                margin-bottom: 4px;
            }}
            .detail-subtitle {{
                color: {MAREX_SOLUTIONS_VIOLET_50} !important;
                font-size: 13px;
                margin-bottom: 12px;
            }}
            .detail-section-title {{
                color: #FFFFFF !important;
                font-size: 14px;
                font-weight: 800;
                margin: 14px 0 8px 0;
            }}
            .description-box {{
                background: {MAREX_BLUE_DARK};
                border: 1px solid {MAREX_GREY_MID};
                border-radius: 10px;
                padding: 12px;
                color: {MAREX_GREY_LIGHT} !important;
                max-height: 210px;
                overflow-y: auto;
                line-height: 1.45;
                margin-bottom: 12px;
            }}
            .detail-row {{
                display: grid;
                grid-template-columns: 165px 1fr;
                gap: 8px;
                padding: 7px 0;
                border-bottom: 1px solid rgba(80, 80, 104, 0.45);
            }}
            .detail-key {{
                color: {MAREX_GREY_MID_70} !important;
                font-weight: 700;
            }}
            .detail-value {{
                color: {MAREX_GREY_LIGHT} !important;
                word-break: break-word;
            }}
            .positive {{ color: {MAREX_GREEN} !important; font-weight: 800; }}
            .negative {{ color: {MAREX_CORAL} !important; font-weight: 800; }}
            .neutral {{ color: {MAREX_GREY_LIGHT} !important; }}

            /* Fallback styling for native Streamlit dataframe when AgGrid is not installed. */
            div[data-testid='stDataFrame'] {{
                background: {MAREX_BLUE_DARKER} !important;
                border: 1px solid {MAREX_BLUE_DARK} !important;
                border-radius: 12px !important;
                overflow: hidden !important;
            }}
            div[data-testid='stDataFrame'] * {{
                color: {MAREX_GREY_LIGHT} !important;
            }}
            [data-testid='stTabs'] button p {{
                color: {MAREX_GREY_LIGHT} !important;
                font-weight: 700 !important;
            }}
            [data-testid='stTabs'] button[aria-selected='true'] p {{
                color: #FFFFFF !important;
            }}
            [data-testid='stTabs'] [role='tablist'] {{
                gap: 4px;
                border-bottom: 1px solid {MAREX_BLUE_DARK};
            }}
            [data-testid='stTabs'] button[role='tab'] {{
                background: {MAREX_BLUE_DARK} !important;
                border-radius: 10px 10px 0 0 !important;
                padding: 8px 12px !important;
            }}
            [data-testid='stTabs'] button[aria-selected='true'] {{
                background: {MAREX_SOLUTIONS_VIOLET_DARKER} !important;
            }}
        </style>
        """,
        unsafe_allow_html=True,
    )


PERCENT_VALUE_FORMATTER = (
    JsCode("""
function(params) {
    if (params.value === null || params.value === undefined || params.value === '') {
        return '';
    }
    const value = Number(params.value);
    if (Number.isNaN(value)) {
        return '';
    }
    return value.toFixed(2) + '%';
}
""")
    if JsCode is not None
    else None
)


AGGRID_CSS = {
    ".ag-root-wrapper": {
        "background-color": f"{MAREX_BLUE_DARKER} !important",
        "border": f"1px solid {MAREX_BLUE_DARK} !important",
        "border-radius": "12px !important",
        "overflow": "hidden !important",
    },
    ".ag-header": {
        "background-color": f"{MAREX_BLUE_DARK} !important",
        "color": "#FFFFFF !important",
        "border-bottom": f"1px solid {MAREX_GREY_MID} !important",
    },
    ".ag-header-cell": {
        "background-color": f"{MAREX_BLUE_DARK} !important",
        "color": "#FFFFFF !important",
        "font-weight": "800 !important",
        "border-right": f"1px solid {MAREX_GREY_MID} !important",
    },
    ".ag-header-cell-text": {"color": "#FFFFFF !important"},
    ".ag-row": {
        "background-color": f"{MAREX_BLUE_DARKER} !important",
        "color": f"{MAREX_GREY_LIGHT} !important",
        "border-bottom": f"1px solid {MAREX_BLUE_DARK} !important",
    },
    ".ag-row-odd": {"background-color": f"{MAREX_ROW_ALT} !important"},
    ".ag-cell": {
        "color": f"{MAREX_GREY_LIGHT} !important",
        "border-right": f"1px solid {MAREX_BLUE_DARK} !important",
    },
    ".ag-row-hover": {"background-color": f"{MAREX_SOLUTIONS_VIOLET_DARKEST} !important"},
    ".ag-row-selected": {
        "background-color": f"{MAREX_SOLUTIONS_VIOLET_DARKER} !important",
        "color": "#FFFFFF !important",
    },
    ".ag-row-selected .ag-cell": {"color": "#FFFFFF !important"},
    ".ag-paging-panel": {
        "background-color": f"{MAREX_BLUE_DARKER} !important",
        "color": f"{MAREX_GREY_LIGHT} !important",
        "border-top": f"1px solid {MAREX_BLUE_DARK} !important",
    },
    ".ag-icon": {"color": f"{MAREX_GREY_LIGHT} !important"},
}


def render_header(excel_path: Path, sheet_name: str, row_count: int) -> None:
    st.markdown(
        f"""
        <div class='marex-header'>
            <div class='marex-title'>MAREX SOLUTIONS</div>
            <div class='marex-subtitle'>Yahoo Finance Stock Screener - Web Dashboard</div>
            <div class='source-line'>
                <span class='status-chip'>Loaded</span>
                <span class='source-chip'>Source: {escape(excel_path)}</span>
                <span class='source-chip'>Sheet: {escape(sheet_name)}</span>
                <span class='source-chip'>{row_count:,} total rows</span>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_toolbar(uploaded_excel_key: str) -> Optional[Any]:
    toolbar_cols = st.columns([1.0, 1.35, 1.2, 3.0], gap="small")
    with toolbar_cols[0]:
        if st.button("Reload Excel", use_container_width=True):
            st.cache_data.clear()
            st.rerun()
    with toolbar_cols[1]:
        enable_refresh = to_bool(get_secret_or_env("ENABLE_REFRESH", False), default=False)
        if enable_refresh:
            if st.button("Refresh Yahoo Finance", use_container_width=True):
                refresh_password = get_secret_or_env("REFRESH_PASSWORD", None)
                entered_refresh_password = st.session_state.get("refresh_password", "")
                if refresh_password and entered_refresh_password != str(refresh_password):
                    st.error("Invalid refresh password")
                else:
                    with st.spinner("Running main.py. This can take several minutes..."):
                        try:
                            code, out, err = run_extraction_script()
                            st.cache_data.clear()
                            if code == 0:
                                st.success("Extraction completed. Data reloaded.")
                                if out:
                                    st.text_area("Extraction output", out, height=180)
                                st.rerun()
                            else:
                                st.error(f"Extraction failed with exit code {code}")
                                if out:
                                    st.text_area("stdout", out, height=160)
                                if err:
                                    st.text_area("stderr", err, height=160)
                        except subprocess.TimeoutExpired:
                            st.error("Extraction timeout reached.")
                        except Exception as exc:
                            st.error(f"Extraction error: {exc}")
        else:
            st.button("Refresh disabled", use_container_width=True, disabled=True)
    with toolbar_cols[2]:
        if to_bool(get_secret_or_env("ENABLE_REFRESH", False), default=False) and get_secret_or_env("REFRESH_PASSWORD", None):
            st.text_input("Refresh password", type="password", key="refresh_password", label_visibility="collapsed", placeholder="Refresh password")
    with toolbar_cols[3]:
        uploaded_excel = st.file_uploader(
            "Upload Excel for this session",
            type=["xlsx", "xlsm", "xls"],
            key=uploaded_excel_key,
            label_visibility="collapsed",
        )
    return uploaded_excel

def render_filters(df_raw: pd.DataFrame) -> dict[str, Any]:
    st.markdown(
        """
        <div class='filters-title-row'>
            <div class='section-title'>Filters</div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    top = st.columns([2.1, 1.25, 1.15, 1.0, 1.65, 0.85], gap="small")
    with top[0]:
        search_text = st.text_input("Search", placeholder="Ticker, company, sector, country...", key="filter_search")
    with top[1]:
        sector_values = ["All"]
        if "sector" in df_raw.columns:
            sector_values += sorted({normalize_text(x) for x in df_raw["sector"].dropna() if normalize_text(x)})
        sector_index = 0
        if st.session_state.get("filter_sector") in sector_values:
            sector_index = sector_values.index(st.session_state.get("filter_sector"))
        sector_filter = st.selectbox("Sector", sector_values, index=sector_index, key="filter_sector")
    with top[2]:
        country_values = ["All"]
        if "country" in df_raw.columns:
            country_values += sorted({normalize_text(x) for x in df_raw["country"].dropna() if normalize_text(x)})
        country_index = 0
        if st.session_state.get("filter_country") in country_values:
            country_index = country_values.index(st.session_state.get("filter_country"))
        country_filter = st.selectbox("Country", country_values, index=country_index, key="filter_country")
    with top[3]:
        currency_values = ["All"]
        if "currency" in df_raw.columns:
            currency_values += sorted({normalize_text(x) for x in df_raw["currency"].dropna() if normalize_text(x)})
        currency_index = 0
        if st.session_state.get("filter_currency") in currency_values:
            currency_index = currency_values.index(st.session_state.get("filter_currency"))
        currency_filter = st.selectbox("Currency", currency_values, index=currency_index, key="filter_currency")
    with top[4]:
        bucket_values = list(MARKET_CAP_BUCKETS.keys())
        bucket_index = 0
        if st.session_state.get("filter_market_cap_bucket") in bucket_values:
            bucket_index = bucket_values.index(st.session_state.get("filter_market_cap_bucket"))
        market_cap_bucket = st.selectbox("Market cap", bucket_values, index=bucket_index, key="filter_market_cap_bucket")
    with top[5]:
        st.write("")
        st.write("")
        st.button("Reset filters", on_click=reset_filters, use_container_width=True)

    c = st.columns(7, gap="small")
    vol_bucket_values = list(VOL_STRIKE_BUCKETS.keys())
    vol_bucket_index = 0
    if st.session_state.get("filter_var_vol_bucket") in vol_bucket_values:
        vol_bucket_index = vol_bucket_values.index(st.session_state.get("filter_var_vol_bucket"))
    var_vol_bucket = c[0].selectbox("Vol strike", vol_bucket_values, index=vol_bucket_index, key="filter_var_vol_bucket")
    pe_min = parse_float_input(c[1].text_input("P/E min", key="filter_pe_min"))
    pe_max = parse_float_input(c[2].text_input("P/E max", key="filter_pe_max"))
    ytd_min_pct = parse_float_input(c[3].text_input("YTD % min", key="filter_ytd_min"))
    ytd_max_pct = parse_float_input(c[4].text_input("YTD % max", key="filter_ytd_max"))
    one_week_min_pct = parse_float_input(c[5].text_input("1W % min", key="filter_1w_min"))
    one_week_max_pct = parse_float_input(c[6].text_input("1W % max", key="filter_1w_max"))

    return {
        "search_text": search_text,
        "sector_filter": sector_filter,
        "country_filter": country_filter,
        "currency_filter": currency_filter,
        "market_cap_bucket": market_cap_bucket,
        "var_vol_bucket": var_vol_bucket,
        "pe_min": pe_min,
        "pe_max": pe_max,
        "ytd_min_pct": ytd_min_pct,
        "ytd_max_pct": ytd_max_pct,
        "one_week_min_pct": one_week_min_pct,
        "one_week_max_pct": one_week_max_pct,
    }



def render_detail_panel(row: Optional[pd.Series]) -> None:
    if row is None:
        st.markdown(
            """
            <div class='right-card'>
                <div class='detail-title'>No ticker selected</div>
                <div class='detail-subtitle'>Click a row in the table to display ticker details.</div>
            </div>
            """,
            unsafe_allow_html=True,
        )
        return

    ticker = normalize_text(row.get("ticker"))
    company = normalize_text(row.get("company_name"))
    sector = normalize_text(row.get("sector"))
    country = normalize_text(row.get("country"))
    currency = normalize_text(row.get("currency"))
    subtitle = " | ".join([x for x in [company, sector, country, currency] if x])
    description = normalize_text(row.get("company_description")) or "No description available."

    details_html: list[str] = [
        "<div class='right-card'>",
        f"<div class='detail-title'>{escape(ticker or 'Ticker')}</div>",
    ]
    if subtitle:
        details_html.append(f"<div class='detail-subtitle'>{escape(subtitle)}</div>")

    details_html.extend(
        [
            "<div class='detail-section-title'>Company description</div>",
            f"<div class='description-box'>{escape(description)}</div>",
            "<div class='detail-section-title'>Ticker details</div>",
        ]
    )

    for field in DETAIL_FIELDS:
        if field not in row.index:
            continue
        label = DISPLAY_NAMES.get(field, field)
        value = format_cell_value(field, row.get(field)) or "-"
        value_class = "detail-value"
        if field in {"YTD return", "1 week return"}:
            raw_val = safe_float(row.get(field))
            if raw_val is not None and raw_val > 0:
                value_class += " positive"
            elif raw_val is not None and raw_val < 0:
                value_class += " negative"
        details_html.append(
            "<div class='detail-row'>"
            f"<div class='detail-key'>{escape(label)}</div>"
            f"<div class='{value_class}'>{escape(value)}</div>"
            "</div>"
        )

    details_html.append("</div>")
    st.markdown("\n".join(details_html), unsafe_allow_html=True)


def render_chart(df: pd.DataFrame) -> None:
    st.markdown("<div class='section-title'>Top variance swap vol strike %</div>", unsafe_allow_html=True)
    if df.empty or "ticker" not in df.columns or "variance_swap_strike_vol_pct" not in df.columns:
        st.info("No chart data available.")
        return

    plot_df = df[["ticker", "variance_swap_strike_vol_pct"]].copy()
    plot_df["variance_swap_strike_vol_pct"] = pd.to_numeric(plot_df["variance_swap_strike_vol_pct"], errors="coerce")
    plot_df = plot_df.dropna().sort_values("variance_swap_strike_vol_pct", ascending=False).head(15)

    if plot_df.empty:
        st.info("No usable variance swap volatility data.")
        return

    fig = px.bar(
        plot_df.sort_values("variance_swap_strike_vol_pct", ascending=True),
        x="variance_swap_strike_vol_pct",
        y="ticker",
        orientation="h",
        labels={"variance_swap_strike_vol_pct": "Vol strike %", "ticker": "Ticker"},
        text="variance_swap_strike_vol_pct",
    )
    fig.update_traces(marker_color=MAREX_SOLUTIONS_VIOLET, texttemplate="%{text:.2f}%", textposition="outside")
    fig.update_layout(
        template="plotly_dark",
        paper_bgcolor=MAREX_BLUE_DARKER,
        plot_bgcolor=MAREX_BLUE_DARKEST,
        font_color=MAREX_GREY_LIGHT,
        height=430,
        margin=dict(l=10, r=10, t=20, b=10),
        xaxis=dict(gridcolor=MAREX_BLUE_DARK, zerolinecolor=MAREX_GREY_MID),
        yaxis=dict(gridcolor=MAREX_BLUE_DARK),
    )
    st.plotly_chart(fig, use_container_width=True)


def get_selected_row_from_streamlit_event(event: Any, filtered_df: pd.DataFrame) -> Optional[pd.Series]:
    if filtered_df.empty:
        return None

    selected_rows: list[int] = []
    try:
        selected_rows = list(event.selection.rows)
    except Exception:
        try:
            selected_rows = list(event.get("selection", {}).get("rows", []))
        except Exception:
            selected_rows = []

    if selected_rows:
        row_pos = selected_rows[0]
        if 0 <= row_pos < len(filtered_df):
            return filtered_df.iloc[row_pos]

    return fallback_selected_row(filtered_df)


def get_selected_row_from_aggrid(selected_rows: Any, filtered_df: pd.DataFrame) -> Optional[pd.Series]:
    if filtered_df.empty:
        return None

    selected_record: Optional[dict[str, Any]] = None
    if selected_rows is None:
        selected_record = None
    elif isinstance(selected_rows, pd.DataFrame):
        if not selected_rows.empty:
            selected_record = selected_rows.iloc[0].to_dict()
    elif isinstance(selected_rows, list):
        if selected_rows:
            first = selected_rows[0]
            if isinstance(first, dict):
                selected_record = first
    elif isinstance(selected_rows, dict):
        selected_record = selected_rows

    if selected_record:
        ticker = normalize_text(selected_record.get("ticker"))
        matched = get_selected_row_by_ticker(ticker, filtered_df)
        if matched is not None:
            return matched

    return fallback_selected_row(filtered_df)


def render_selectable_table(table_df: pd.DataFrame, filtered_df: pd.DataFrame) -> Optional[pd.Series]:
    if table_df.empty:
        st.warning("No rows match the current filters.")
        return None

    if AGGRID_AVAILABLE:
        gb = GridOptionsBuilder.from_dataframe(table_df)
        gb.configure_default_column(sortable=True, filter=True, resizable=True, min_column_width=92)
        gb.configure_selection("single", use_checkbox=False)
        gb.configure_grid_options(
            domLayout="normal",
            rowHeight=34,
            headerHeight=38,
            suppressRowHoverHighlight=False,
            animateRows=False,
            enableCellTextSelection=True,
            ensureDomOrder=True,
        )

        for col in table_df.columns:
            header = DISPLAY_NAMES.get(col, col)
            width = 120
            if col == "ticker":
                width = 95
                gb.configure_column(col, header_name=header, pinned="left", width=width)
            elif col == "company_name":
                width = 245
                gb.configure_column(col, header_name=header, width=width)
            elif col == "sector":
                width = 170
                gb.configure_column(col, header_name=header, width=width)
            elif col == "country":
                width = 135
                gb.configure_column(col, header_name=header, width=width)
            elif col in {"YTD return", "1 week return", "dividend_yield", "variance_swap_strike_vol", "variance_swap_strike_vol_pct"}:
                width = 125
                gb.configure_column(
                    col,
                    header_name=header,
                    width=width,
                    type=["numericColumn"],
                    valueFormatter=PERCENT_VALUE_FORMATTER,
                )
            elif col in NUMERIC_COLUMNS:
                width = 125
                gb.configure_column(col, header_name=header, width=width, type=["numericColumn"])
            else:
                gb.configure_column(col, header_name=header, width=width)

        response = AgGrid(
            table_df,
            gridOptions=gb.build(),
            height=620,
            width="100%",
            data_return_mode=DataReturnMode.FILTERED_AND_SORTED,
            update_mode=GridUpdateMode.SELECTION_CHANGED,
            fit_columns_on_grid_load=False,
            theme="alpine",
            custom_css=AGGRID_CSS,
            allow_unsafe_jscode=True,
            key="marex_universe_aggrid",
        )
        selected_row = get_selected_row_from_aggrid(response.get("selected_rows"), filtered_df)
    else:
        event = st.dataframe(
            table_df,
            hide_index=True,
            use_container_width=True,
            height=620,
            column_config=build_column_config(table_df),
            on_select="rerun",
            selection_mode="single-row",
            key="marex_universe_table",
        )
        selected_row = get_selected_row_from_streamlit_event(event, filtered_df)

    if selected_row is not None and "ticker" in selected_row.index:
        st.session_state["selected_ticker"] = normalize_text(selected_row.get("ticker"))

    return selected_row


# -----------------------------------------------------------------------------
# Streamlit app
# -----------------------------------------------------------------------------

st.set_page_config(
    page_title="Marex Solutions - Stock Screener",
    page_icon="M",
    layout="wide",
    initial_sidebar_state="collapsed",
)

inject_css()
require_password_if_configured()

excel_path = get_excel_path()
sheet_name = get_sheet_name()
uploaded_excel_state = st.session_state.get("uploaded_excel")

file_path_str, file_mtime_ns, file_size = get_file_signature(excel_path)
try:
    if uploaded_excel_state is not None:
        raw_df = pd.read_excel(uploaded_excel_state, sheet_name=sheet_name)
        df_raw = clean_dataframe(raw_df)
        data_source_label = Path(uploaded_excel_state.name)
    else:
        df_raw = read_dashboard_excel(file_path_str, sheet_name, file_mtime_ns, file_size)
        data_source_label = excel_path
except Exception as exc:
    render_header(excel_path, sheet_name, 0)
    st.error(f"Unable to load data: {exc}")
    st.stop()

render_header(data_source_label, sheet_name, len(df_raw))
render_toolbar("uploaded_excel")

filter_values = render_filters(df_raw)
filtered_df = filter_dataframe(
    df=df_raw,
    search_text=filter_values["search_text"],
    sector=filter_values["sector_filter"],
    country=filter_values["country_filter"],
    currency=filter_values["currency_filter"],
    market_cap_bucket=filter_values["market_cap_bucket"],
    var_vol_bucket=filter_values["var_vol_bucket"],
    pe_min=filter_values["pe_min"],
    pe_max=filter_values["pe_max"],
    ytd_min_pct=filter_values["ytd_min_pct"],
    ytd_max_pct=filter_values["ytd_max_pct"],
    one_week_min_pct=filter_values["one_week_min_pct"],
    one_week_max_pct=filter_values["one_week_max_pct"],
)

if "selected_ticker" not in st.session_state:
    st.session_state["selected_ticker"] = None

left_col, right_col = st.columns([2.18, 1.0], gap="large")

with left_col:
    st.markdown(
        f"""
        <div class='panel-title-row'>
            <div class='section-title'>Universe</div>
        </div>
        """,
        unsafe_allow_html=True,
    )
    table_df = prepare_table_dataframe(filtered_df)
    selected_row = render_selectable_table(table_df, filtered_df)
    st.markdown(
        f"<div class='muted-text'>{len(filtered_df):,} visible row(s) / {len(df_raw):,} total</div>",
        unsafe_allow_html=True,
    )

    csv_df = prepare_table_dataframe(filtered_df)
    csv_data = csv_df.to_csv(index=False).encode("utf-8-sig")
    st.download_button(
        "Download filtered view as CSV",
        data=csv_data,
        file_name="marex_stock_screener_view.csv",
        mime="text/csv",
        use_container_width=True,
    )

with right_col:
    detail_tab, chart_tab = st.tabs(["Ticker details", "Dashboard"])
    with detail_tab:
        render_detail_panel(selected_row)
    with chart_tab:
        render_chart(filtered_df)
