# -*- coding: utf-8 -*-
"""
Marex Solutions - Yahoo Finance Stock Screener Web App

Dark Streamlit web application reading the Excel file generated by main.py:
- Stock Screener.xlsx
- extraction YF sheet

This version uses the Marex / Marex Solutions palette and mirrors the previous
desktop layout: header, toolbar, filters, filters and a full-width table. Ticker details and correlation
matrices open in modal dialogs. KPI cards above the table were removed.
"""

from __future__ import annotations

import html
import json
import math
import os
import subprocess
import sys
from pathlib import Path
from typing import Any, Optional

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st
import streamlit.components.v1 as components

try:
    from st_aggrid import AgGrid, DataReturnMode, GridOptionsBuilder, GridUpdateMode, JsCode

    AGGRID_AVAILABLE = True
except Exception:
    JsCode = None
    AGGRID_AVAILABLE = False


APP_DIR = Path(__file__).resolve().parent
DEFAULT_EXCEL_NAME = "Stock Screener.xlsx"
DEFAULT_OUTPUT_SHEET = "extraction YF"
DEFAULT_PARAM_SHEET = "params"
CORRELATION_SHEET = "correlation matrix"
DEFAULT_MAIN_SCRIPT = "main.py"
PARAM_TICKER_COLUMN = "ticker"
UNIVERSE_COLUMN = "universe"

# Marex / Marex Solutions palette.
MAREX_BLUE_DARKEST = "#0E0D24"
MAREX_BLUE_DARKER = "#121230"
MAREX_BLUE_DARK = "#1C1B4A"
MAREX_SOLUTIONS_VIOLET = "#843FDC"
MAREX_SOLUTIONS_VIOLET_DARKER = "#4D2480"
MAREX_SOLUTIONS_VIOLET_DARKEST = "#1F0F33"
MAREX_SOLUTIONS_VIOLET_50 = "#CF9EED"
MAREX_SOLUTIONS_VIOLET_20 = "#ECD9F8"
MAREX_GREY_LIGHT = "#DADAE7"
MAREX_GREY_LIGHT_30 = "#F5F5F8"
MAREX_GREY_MID = "#505068"
MAREX_GREY_MID_70 = "#858596"
MAREX_GREEN = "#2D8D79"
MAREX_CORAL = "#FF846A"
MAREX_ROW_ALT = "#171735"

PREFERRED_COLUMNS = [
    "ticker",
    "company_name",
    "company_description",
    "close_price",
    "YTD return",
    "1 week return",
    "Current target",
    "Upgrades / downgrades",
    "Analyst recommendations",
    "sector",
    "country",
    "universe",
    "next_earnings_date",
    "dividend_yield",
    "market_cap",
    "currency",
    "price_earnings_ratio",
    "variance_swap_target_dte",
    "variance_swap_selected_dte",
    "variance_swap_selected_expiration",
    "variance_swap_strike_variance",
    "variance_swap_strike_vol",
    "variance_swap_strike_vol_pct",
    "variance_swap_strike_vol_pct_180d",
    "variance_swap_strike_vol_pct_360d",
    "variance_swap_forward_price",
    "variance_swap_k0",
    "variance_swap_options_used",
    "extraction_datetime",
]

# Columns kept for ticker details but hidden from the main table.
TABLE_HIDDEN_COLUMNS = {
    "company_description",
    "close_price",
    "universe",
    "Current target",
    "Upgrades / downgrades",
    "Analyst recommendations",
    "market_cap",
    "variance_swap_target_dte",
    "variance_swap_selected_dte",
    "variance_swap_selected_expiration",
    "variance_swap_forward_price",
    "variance_swap_options_used",
    "extraction_datetime",
}

NUMERIC_COLUMNS = {
    "close_price",
    "YTD return",
    "1 week return",
    "Current target",
    "dividend_yield",
    "market_cap",
    "price_earnings_ratio",
    "variance_swap_target_dte",
    "variance_swap_selected_dte",
    "variance_swap_strike_variance",
    "variance_swap_strike_vol",
    "variance_swap_strike_vol_pct",
    "variance_swap_strike_vol_pct_180d",
    "variance_swap_strike_vol_pct_360d",
    "variance_swap_forward_price",
    "variance_swap_k0",
    "variance_swap_options_used",
}

DATE_COLUMNS = {
    "next_earnings_date",
    "variance_swap_selected_expiration",
    "extraction_datetime",
}

DISPLAY_NAMES = {
    "ticker": "Ticker",
    "company_name": "Company",
    "company_description": "Description",
    "close_price": "Close",
    "YTD return": "YTD return",
    "1 week return": "1W return",
    "Current target": "Current target",
    "Upgrades / downgrades": "Upgrades / downgrades",
    "Analyst recommendations": "Analyst recommendations",
    "sector": "Sector",
    "country": "Country",
    "universe": "Universe",
    "next_earnings_date": "Next earnings",
    "dividend_yield": "Div. yield",
    "market_cap": "Market cap",
    "currency": "Currency",
    "price_earnings_ratio": "P/E",
    "variance_swap_target_dte": "Target DTE",
    "variance_swap_selected_dte": "Selected DTE",
    "variance_swap_selected_expiration": "Expiry",
    "variance_swap_strike_variance": "Var strike",
    "variance_swap_strike_vol": "Vol strike",
    "variance_swap_strike_vol_pct": "Vol 30D %",
    "variance_swap_strike_vol_pct_180d": "Vol 180D %",
    "variance_swap_strike_vol_pct_360d": "Vol 360D %",
    "variance_swap_forward_price": "Forward",
    "variance_swap_k0": "K0",
    "variance_swap_options_used": "Options used",
    "extraction_datetime": "Extracted at",
}

DETAIL_FIELDS = [
    "ticker",
    "company_name",
    "sector",
    "country",
    "universe",
    "currency",
    "close_price",
    "YTD return",
    "1 week return",
    "Current target",
    "market_cap",
    "price_earnings_ratio",
    "dividend_yield",
    "next_earnings_date",
    "Upgrades / downgrades",
    "Analyst recommendations",
    "variance_swap_target_dte",
    "variance_swap_selected_dte",
    "variance_swap_selected_expiration",
    "variance_swap_strike_vol_pct",
    "variance_swap_strike_vol_pct_180d",
    "variance_swap_strike_vol_pct_360d",
    "variance_swap_strike_variance",
    "variance_swap_forward_price",
    "variance_swap_k0",
    "variance_swap_options_used",
    "extraction_datetime",
]

TABLE_COLUMNS = [col for col in PREFERRED_COLUMNS if col not in TABLE_HIDDEN_COLUMNS]
FILTER_STATE_KEYS = [
    "filter_search",
    "filter_sector",
    "filter_country",
    "filter_currency",
    "filter_universe",
    "filter_market_cap_bucket",
    "filter_var_vol_bucket",
    # Legacy keys from the old min/max volatility inputs. Kept here so Reset filters
    # clears old Streamlit session state if the app was already open in the browser.
    "filter_var_vol_min",
    "filter_var_vol_max",
    "filter_pe_min",
    "filter_pe_max",
    "filter_ytd_min",
    "filter_ytd_max",
    "filter_1w_min",
    "filter_1w_max",
]

MARKET_CAP_BUCKETS = {
    "All": (None, None),
    "Mega Cap > 200 milliards": (200_000_000_000, None),
    "Large Cap 10-200 milliards": (10_000_000_000, 200_000_000_000),
    "Mid Cap 2-10 milliards": (2_000_000_000, 10_000_000_000),
    "Small Cap < 2 milliards": (None, 2_000_000_000),
}

VOL_STRIKE_BUCKETS = {
    "All": (None, None),
    "Very High Vol > 60%": (60.0, None),
    "High Vol 40%-60%": (40.0, 60.0),
    "Mid Vol 20%-40%": (20.0, 40.0),
    "Low Vol < 20%": (None, 20.0),
}


# -----------------------------------------------------------------------------
# Generic helpers
# -----------------------------------------------------------------------------

def is_null(value: Any) -> bool:
    if value is None:
        return True
    try:
        return bool(pd.isna(value))
    except Exception:
        return False


def safe_float(value: Any) -> Optional[float]:
    if is_null(value):
        return None
    if isinstance(value, (int, float, np.integer, np.floating)):
        val = float(value)
        return val if math.isfinite(val) else None
    if isinstance(value, str):
        cleaned = (
            value.strip()
            .replace("%", "")
            .replace(",", "")
            .replace(" ", "")
            .replace("\u00a0", "")
        )
        if not cleaned:
            return None
        try:
            val = float(cleaned)
            return val if math.isfinite(val) else None
        except ValueError:
            return None
    return None


def normalize_text(value: Any) -> str:
    if is_null(value):
        return ""
    return str(value).strip()


def escape(value: Any) -> str:
    return html.escape(normalize_text(value))


def human_number(value: Any, decimals: int = 1) -> str:
    val = safe_float(value)
    if val is None:
        return ""
    abs_val = abs(val)
    if abs_val >= 1_000_000_000_000:
        return f"{val / 1_000_000_000_000:,.{decimals}f}T"
    if abs_val >= 1_000_000_000:
        return f"{val / 1_000_000_000:,.{decimals}f}B"
    if abs_val >= 1_000_000:
        return f"{val / 1_000_000:,.{decimals}f}M"
    if abs_val >= 1_000:
        return f"{val / 1_000:,.{decimals}f}K"
    return f"{val:,.{decimals}f}"


def format_date(value: Any) -> str:
    if is_null(value):
        return ""
    try:
        ts = pd.to_datetime(value, errors="coerce")
    except Exception:
        return str(value)
    if pd.isna(ts):
        return str(value)
    if getattr(ts, "tzinfo", None) is not None:
        try:
            ts = ts.tz_convert(None)
        except Exception:
            ts = ts.tz_localize(None)
    if getattr(ts, "hour", 0) == 0 and getattr(ts, "minute", 0) == 0 and getattr(ts, "second", 0) == 0:
        return ts.strftime("%Y-%m-%d")
    return ts.strftime("%Y-%m-%d %H:%M")


def format_percent(value: Any, column: str) -> str:
    val = safe_float(value)
    if val is None:
        return ""
    if column in {"YTD return", "1 week return"}:
        # Stock returns are stored as decimals in Excel: 0.05 = 5%.
        val *= 100
    elif column in {"dividend_yield", "variance_swap_strike_vol"}:
        if abs(val) <= 2:
            val *= 100
    return f"{val:,.2f}%"


def format_cell_value(column: str, value: Any) -> str:
    if is_null(value):
        return ""
    if column in DATE_COLUMNS or "date" in column.lower() or "expiration" in column.lower():
        return format_date(value)
    if column == "market_cap":
        return human_number(value)
    if column in {"dividend_yield", "YTD return", "1 week return", "variance_swap_strike_vol", "variance_swap_strike_vol_pct", "variance_swap_strike_vol_pct_180d", "variance_swap_strike_vol_pct_360d"}:
        return format_percent(value, column)
    if column in NUMERIC_COLUMNS:
        val = safe_float(value)
        if val is None:
            return ""
        if abs(val) >= 1000:
            return f"{val:,.0f}"
        return f"{val:,.2f}"
    return str(value)


def reorder_columns(df: pd.DataFrame) -> pd.DataFrame:
    existing = [col for col in PREFERRED_COLUMNS if col in df.columns]
    remaining = [col for col in df.columns if col not in existing]
    return df[existing + remaining]


def clean_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df.columns = [str(c).strip() for c in df.columns]

    for col in df.columns:
        if col in NUMERIC_COLUMNS:
            df[col] = pd.to_numeric(df[col], errors="coerce")
        elif col in DATE_COLUMNS or "date" in col.lower() or "expiration" in col.lower():
            df[col] = pd.to_datetime(df[col], errors="coerce")
            try:
                if getattr(df[col].dt, "tz", None) is not None:
                    df[col] = df[col].dt.tz_localize(None)
            except Exception:
                pass

    return reorder_columns(df)


def get_secret_or_env(name: str, default: Any = None) -> Any:
    """Read from Streamlit secrets first, then environment variables."""
    for key in (name, name.lower(), name.upper()):
        try:
            if key in st.secrets:
                return st.secrets[key]
        except Exception:
            pass
        if key in os.environ:
            return os.environ[key]
    return default


def to_bool(value: Any, default: bool = False) -> bool:
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"1", "true", "yes", "y", "on"}


def get_excel_path() -> Path:
    configured = get_secret_or_env("EXCEL_PATH", None)
    if configured:
        return Path(str(configured)).expanduser()
    return APP_DIR / DEFAULT_EXCEL_NAME


def get_sheet_name() -> str:
    return str(get_secret_or_env("OUTPUT_SHEET", DEFAULT_OUTPUT_SHEET))


def get_file_signature(path: Path) -> tuple[str, int, int]:
    if not path.exists():
        return (str(path), 0, 0)
    stat = path.stat()
    return (str(path), stat.st_mtime_ns, stat.st_size)


def find_case_insensitive_column(df: pd.DataFrame, target: str) -> Optional[str]:
    """Return the actual column name matching target, ignoring case and spaces."""
    target_clean = str(target).strip().lower()
    for col in df.columns:
        if str(col).strip().lower() == target_clean:
            return str(col)
    return None


def parse_universe_values(value: Any) -> list[str]:
    """
    Split a params-sheet universe cell into individual universe names.

    Example:
        "SX5E ; CAC40" -> ["SX5E", "CAC40"]
    """
    if is_null(value):
        return []
    text = str(value).replace("\r", "\n").replace("|", ";").replace(",", ";")
    parts: list[str] = []
    seen = set()
    for chunk in text.replace("\n", ";").split(";"):
        universe = " ".join(str(chunk).split()).strip()
        if universe and universe not in seen:
            parts.append(universe)
            seen.add(universe)
    return parts

def format_universe_value(value: Any) -> str:
    return " ; ".join(parse_universe_values(value))


def combine_universe_series(values: pd.Series) -> str:
    combined: list[str] = []
    seen = set()
    for value in values:
        for universe in parse_universe_values(value):
            if universe not in seen:
                combined.append(universe)
                seen.add(universe)
    return " ; ".join(combined)


def collect_universe_options(series: pd.Series) -> list[str]:
    options: list[str] = []
    seen = set()
    for value in series.dropna():
        for universe in parse_universe_values(value):
            if universe not in seen:
                options.append(universe)
                seen.add(universe)
    return sorted(options, key=lambda x: x.upper())


def merge_universe_from_params(extraction_df: pd.DataFrame, params_df: pd.DataFrame) -> pd.DataFrame:
    """
    Attach the params-sheet universe column to the extraction dataframe by ticker.

    The extraction sheet is left untouched on disk. This merge is done at read time
    so the app can filter on params['universe'] even when main.py rewrites only the
    'extraction YF' sheet.
    """
    if extraction_df is None or extraction_df.empty or params_df is None or params_df.empty:
        return extraction_df

    df = extraction_df.copy()
    params = params_df.copy()

    df_ticker_col = find_case_insensitive_column(df, PARAM_TICKER_COLUMN)
    params_ticker_col = find_case_insensitive_column(params, PARAM_TICKER_COLUMN)
    params_universe_col = find_case_insensitive_column(params, UNIVERSE_COLUMN)

    if df_ticker_col is None or params_ticker_col is None or params_universe_col is None:
        return df

    mapping = params[[params_ticker_col, params_universe_col]].copy()
    mapping["_ticker_key"] = mapping[params_ticker_col].fillna("").astype(str).str.strip()
    mapping = mapping[mapping["_ticker_key"] != ""]
    if mapping.empty:
        return df

    mapping = (
        mapping.groupby("_ticker_key", as_index=False)[params_universe_col]
        .apply(combine_universe_series)
        .rename(columns={params_universe_col: UNIVERSE_COLUMN})
    )

    df["_ticker_key"] = df[df_ticker_col].fillna("").astype(str).str.strip()
    existing_universe_col = find_case_insensitive_column(df, UNIVERSE_COLUMN)
    if existing_universe_col and existing_universe_col != UNIVERSE_COLUMN:
        df = df.rename(columns={existing_universe_col: UNIVERSE_COLUMN})

    df = df.merge(mapping, on="_ticker_key", how="left", suffixes=("", "_from_params"))
    if f"{UNIVERSE_COLUMN}_from_params" in df.columns:
        if UNIVERSE_COLUMN in df.columns:
            merged_value = df[f"{UNIVERSE_COLUMN}_from_params"].fillna("").astype(str).str.strip()
            current_value = df[UNIVERSE_COLUMN].fillna("").astype(str).str.strip()
            df[UNIVERSE_COLUMN] = merged_value.where(merged_value != "", current_value)
        else:
            df[UNIVERSE_COLUMN] = df[f"{UNIVERSE_COLUMN}_from_params"]
        df = df.drop(columns=[f"{UNIVERSE_COLUMN}_from_params"])

    if UNIVERSE_COLUMN in df.columns:
        df[UNIVERSE_COLUMN] = df[UNIVERSE_COLUMN].apply(format_universe_value)

    return df.drop(columns=["_ticker_key"], errors="ignore")


@st.cache_data(ttl=60, show_spinner=False)
def read_dashboard_excel(path_str: str, sheet_name: str, mtime_ns: int, size: int) -> pd.DataFrame:
    path = Path(path_str)
    if not path.exists():
        raise FileNotFoundError(f"Excel file not found: {path}")
    df = pd.read_excel(path, sheet_name=sheet_name)
    try:
        params_df = pd.read_excel(path, sheet_name=DEFAULT_PARAM_SHEET)
        df = merge_universe_from_params(df, params_df)
    except Exception:
        pass
    return clean_dataframe(df)


def clean_correlation_matrix(df: pd.DataFrame) -> pd.DataFrame:
    """Normalise la matrice de correlation lue depuis Excel."""
    if df is None or df.empty:
        return pd.DataFrame()

    corr = df.copy()
    corr.index = corr.index.astype(str).str.strip()
    corr.columns = [str(c).strip() for c in corr.columns]
    corr = corr.apply(pd.to_numeric, errors="coerce")
    corr = corr.loc[:, ~pd.Index(corr.columns).duplicated()].copy()
    corr = corr[~corr.index.duplicated(keep="first")]
    return corr


@st.cache_data(ttl=60, show_spinner=False)
def read_correlation_matrix_excel(path_str: str, sheet_name: str, mtime_ns: int, size: int) -> pd.DataFrame:
    path = Path(path_str)
    if not path.exists():
        raise FileNotFoundError(f"Excel file not found: {path}")
    corr = pd.read_excel(path, sheet_name=sheet_name, index_col=0)
    return clean_correlation_matrix(corr)


def read_uploaded_correlation_matrix(uploaded_excel: Any) -> pd.DataFrame:
    if uploaded_excel is None:
        return pd.DataFrame()
    try:
        uploaded_excel.seek(0)
    except Exception:
        pass
    corr = pd.read_excel(uploaded_excel, sheet_name=CORRELATION_SHEET, index_col=0)
    return clean_correlation_matrix(corr)


def subset_correlation_matrix(corr: pd.DataFrame, tickers: list[str]) -> pd.DataFrame:
    if corr is None or corr.empty:
        return pd.DataFrame()
    clean_tickers = []
    seen = set()
    for ticker in tickers:
        ticker = str(ticker).strip()
        if ticker and ticker not in seen:
            clean_tickers.append(ticker)
            seen.add(ticker)
    available = [ticker for ticker in clean_tickers if ticker in corr.index and ticker in corr.columns]
    if len(available) < 2:
        return pd.DataFrame()
    return corr.loc[available, available].astype(float)


def build_pairwise_correlation_table(corr_subset: pd.DataFrame) -> pd.DataFrame:
    """
    Transforme une matrice de correlation en tableau de toutes les paires uniques.

    Sortie :
    - Ticker 1
    - Ticker 2
    - Correlation

    La diagonale et les doublons symetriques sont exclus.
    """
    columns = ["Ticker 1", "Ticker 2", "Correlation"]
    if corr_subset is None or corr_subset.empty:
        return pd.DataFrame(columns=columns)

    tickers = [str(ticker).strip() for ticker in corr_subset.index if str(ticker).strip()]
    rows: list[dict[str, Any]] = []

    for i, ticker_1 in enumerate(tickers):
        for ticker_2 in tickers[i + 1:]:
            if ticker_1 not in corr_subset.index or ticker_2 not in corr_subset.columns:
                continue
            correlation = safe_float(corr_subset.loc[ticker_1, ticker_2])
            if correlation is None:
                continue
            rows.append({
                "Ticker 1": ticker_1,
                "Ticker 2": ticker_2,
                "Correlation": correlation,
            })

    if not rows:
        return pd.DataFrame(columns=columns)

    return (
        pd.DataFrame(rows, columns=columns)
        .sort_values(["Correlation", "Ticker 1", "Ticker 2"], ascending=[True, True, True])
        .reset_index(drop=True)
    )


def render_copy_to_clipboard_button(text_to_copy: str, button_label: str = "Copy pairwise table to clipboard") -> None:
    """
    Render a browser-side copy button for tab-separated table data.
    A manual text-area fallback is also displayed below by the caller if needed.
    """
    payload = json.dumps(text_to_copy)
    label = html.escape(button_label)
    components.html(
        f"""
        <div style="display:flex; align-items:center; gap:12px; margin:6px 0 2px 0;">
            <button id="copy-pairwise-corr"
                    style="background:{MAREX_SOLUTIONS_VIOLET}; color:white; border:1px solid {MAREX_SOLUTIONS_VIOLET};
                           border-radius:10px; padding:10px 14px; font-weight:800; cursor:pointer;">
                {label}
            </button>
            <span id="copy-pairwise-corr-status" style="color:{MAREX_GREY_LIGHT}; font-family:Arial, sans-serif; font-size:13px;"></span>
        </div>
        <script>
            const textToCopy = {payload};
            const button = document.getElementById("copy-pairwise-corr");
            const status = document.getElementById("copy-pairwise-corr-status");
            button.addEventListener("click", async () => {{
                try {{
                    await navigator.clipboard.writeText(textToCopy);
                    status.textContent = "Copied to clipboard";
                }} catch (err) {{
                    const textarea = document.createElement("textarea");
                    textarea.value = textToCopy;
                    textarea.style.position = "fixed";
                    textarea.style.left = "-9999px";
                    document.body.appendChild(textarea);
                    textarea.focus();
                    textarea.select();
                    try {{
                        document.execCommand("copy");
                        status.textContent = "Copied to clipboard";
                    }} catch (fallbackErr) {{
                        status.textContent = "Copy failed - use the text area below";
                    }}
                    document.body.removeChild(textarea);
                }}
            }});
        </script>
        """,
        height=58,
    )


def build_search_index(df: pd.DataFrame) -> pd.Series:
    if df.empty:
        return pd.Series(dtype=str)
    candidate_cols = [
        "ticker",
        "company_name",
        "sector",
        "country",
        "currency",
        "universe",
        "company_description",
        "Upgrades / downgrades",
        "Analyst recommendations",
    ]
    cols = [col for col in candidate_cols if col in df.columns]
    if not cols:
        return pd.Series([""] * len(df), index=df.index)
    return df[cols].fillna("").astype(str).agg(" ".join, axis=1).str.lower()


def parse_float_input(value: Any) -> Optional[float]:
    if value is None or value == "":
        return None
    try:
        return float(str(value).replace(",", "."))
    except ValueError:
        return None


def apply_numeric_range(df: pd.DataFrame, column: str, min_value: Optional[float], max_value: Optional[float]) -> pd.DataFrame:
    if column not in df.columns or (min_value is None and max_value is None):
        return df
    values = pd.to_numeric(df[column], errors="coerce")
    mask = pd.Series(True, index=df.index)
    if min_value is not None:
        mask &= values >= min_value
    if max_value is not None:
        mask &= values <= max_value
    return df[mask]


def apply_market_cap_bucket(df: pd.DataFrame, bucket: str) -> pd.DataFrame:
    """
    Filtre par bucket de capitalisation boursiere.
    Les seuils sont appliques directement sur la colonne market_cap renvoyee par Yahoo Finance.
    """
    if not bucket or bucket == "All" or "market_cap" not in df.columns:
        return df

    min_value, max_value = MARKET_CAP_BUCKETS.get(bucket, (None, None))
    values = pd.to_numeric(df["market_cap"], errors="coerce")
    mask = pd.Series(True, index=df.index)

    if min_value is not None:
        mask &= values > min_value if bucket.startswith("Mega Cap") else values >= min_value
    if max_value is not None:
        mask &= values < max_value if bucket.startswith("Small Cap") else values <= max_value

    return df[mask]


def apply_vol_strike_bucket(df: pd.DataFrame, bucket: str) -> pd.DataFrame:
    """
    Filtre par bucket de volatilite variance swap, en pourcentage.
    La colonne variance_swap_strike_vol_pct est deja exprimee en pourcentage.
    """
    if not bucket or bucket == "All" or "variance_swap_strike_vol_pct" not in df.columns:
        return df

    min_value, max_value = VOL_STRIKE_BUCKETS.get(bucket, (None, None))
    values = pd.to_numeric(df["variance_swap_strike_vol_pct"], errors="coerce")
    mask = pd.Series(True, index=df.index)

    if bucket == "Very High Vol > 60%":
        mask &= values > min_value
    elif bucket == "High Vol 40%-60%":
        mask &= (values >= min_value) & (values <= max_value)
    elif bucket == "Mid Vol 20%-40%":
        mask &= (values >= min_value) & (values < max_value)
    elif bucket == "Low Vol < 20%":
        mask &= values < max_value

    return df[mask]


def apply_universe_filter(df: pd.DataFrame, universe: str) -> pd.DataFrame:
    """Filter rows where the selected universe appears in the semicolon-separated universe cell."""
    universe = normalize_text(universe)
    if not universe or universe == "All" or UNIVERSE_COLUMN not in df.columns:
        return df
    mask = df[UNIVERSE_COLUMN].apply(lambda value: universe in parse_universe_values(value))
    return df[mask]


def filter_dataframe(
    df: pd.DataFrame,
    search_text: str,
    sectors: list[str],
    countries: list[str],
    currencies: list[str],
    universe: str,
    market_cap_bucket: str,
    var_vol_bucket: str,
    pe_min: Optional[float],
    pe_max: Optional[float],
    ytd_min_pct: Optional[float],
    ytd_max_pct: Optional[float],
    one_week_min_pct: Optional[float],
    one_week_max_pct: Optional[float],
) -> pd.DataFrame:
    filtered = df.copy()

    search_text = (search_text or "").strip().lower()
    if search_text:
        index = build_search_index(filtered)
        filtered = filtered[index.str.contains(search_text, na=False, regex=False)]

    if sectors and "All" not in sectors and "sector" in filtered.columns:
        filtered = filtered[filtered["sector"].fillna("").astype(str).str.strip().isin(sectors)]

    if countries and "All" not in countries and "country" in filtered.columns:
        filtered = filtered[filtered["country"].fillna("").astype(str).str.strip().isin(countries)]

    if currencies and "All" not in currencies and "currency" in filtered.columns:
        filtered = filtered[filtered["currency"].fillna("").astype(str).str.strip().isin(currencies)]

    filtered = apply_universe_filter(filtered, universe)

    filtered = apply_market_cap_bucket(filtered, market_cap_bucket)
    filtered = apply_vol_strike_bucket(filtered, var_vol_bucket)
    filtered = apply_numeric_range(filtered, "price_earnings_ratio", pe_min, pe_max)

    # Returns are stored as decimals in Excel. User inputs are percentages.
    filtered = apply_numeric_range(
        filtered,
        "YTD return",
        ytd_min_pct / 100 if ytd_min_pct is not None else None,
        ytd_max_pct / 100 if ytd_max_pct is not None else None,
    )
    filtered = apply_numeric_range(
        filtered,
        "1 week return",
        one_week_min_pct / 100 if one_week_min_pct is not None else None,
        one_week_max_pct / 100 if one_week_max_pct is not None else None,
    )

    return filtered



def prepare_table_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    table_cols = [col for col in TABLE_COLUMNS if col in df.columns]
    display = df[table_cols].copy()

    # Convert return columns from decimals to percentages for display in the grid.
    for col in ["YTD return", "1 week return"]:
        if col in display.columns:
            display[col] = pd.to_numeric(display[col], errors="coerce") * 100

    if "dividend_yield" in display.columns:
        div = pd.to_numeric(display["dividend_yield"], errors="coerce")
        display["dividend_yield"] = div.where(div.abs() > 2, div * 100)

    if "variance_swap_strike_vol" in display.columns:
        vol = pd.to_numeric(display["variance_swap_strike_vol"], errors="coerce")
        display["variance_swap_strike_vol"] = vol.where(vol.abs() > 2, vol * 100)

    for col in display.columns:
        if col in DATE_COLUMNS or "date" in col.lower() or "expiration" in col.lower():
            display[col] = display[col].apply(format_date)

    return display


def build_column_config(df: pd.DataFrame) -> dict[str, Any]:
    config: dict[str, Any] = {}

    for col in df.columns:
        label = DISPLAY_NAMES.get(col, col)
        if col in {"YTD return", "1 week return", "dividend_yield", "variance_swap_strike_vol", "variance_swap_strike_vol_pct", "variance_swap_strike_vol_pct_180d", "variance_swap_strike_vol_pct_360d"}:
            config[col] = st.column_config.NumberColumn(label, format="%.2f%%")
        elif col == "market_cap":
            config[col] = st.column_config.NumberColumn(label, format="%.0f")
        elif col in NUMERIC_COLUMNS:
            config[col] = st.column_config.NumberColumn(label, format="%.2f")
        else:
            config[col] = st.column_config.TextColumn(label)

    return config


def get_selected_row_by_ticker(ticker: str, filtered_df: pd.DataFrame) -> Optional[pd.Series]:
    if not ticker or "ticker" not in filtered_df.columns:
        return None
    matches = filtered_df[filtered_df["ticker"].astype(str) == str(ticker)]
    if matches.empty:
        return None
    return matches.iloc[0]


def fallback_selected_row(filtered_df: pd.DataFrame) -> Optional[pd.Series]:
    if filtered_df.empty:
        return None
    saved_ticker = st.session_state.get("selected_ticker")
    if saved_ticker:
        matched = get_selected_row_by_ticker(str(saved_ticker), filtered_df)
        if matched is not None:
            return matched
    return filtered_df.iloc[0]


def reset_filters() -> None:
    for key in FILTER_STATE_KEYS:
        st.session_state.pop(key, None)


def ensure_multiselect_state(key: str, options: list[str]) -> None:
    """
    Converts old single-select session values into valid multiselect values.
    This prevents Streamlit errors after replacing selectboxes by multiselects.
    """
    value = st.session_state.get(key, [])
    if isinstance(value, str):
        value = [] if value == "All" else [value]
    elif value is None:
        value = []
    elif not isinstance(value, list):
        try:
            value = list(value)
        except Exception:
            value = []

    option_set = set(options)
    st.session_state[key] = [normalize_text(v) for v in value if normalize_text(v) in option_set]


def run_extraction_script() -> tuple[int, str, str]:
    script_path = APP_DIR / DEFAULT_MAIN_SCRIPT
    if not script_path.exists():
        return 1, "", f"{DEFAULT_MAIN_SCRIPT} not found in {APP_DIR}"

    timeout_seconds = int(get_secret_or_env("REFRESH_TIMEOUT_SECONDS", 60 * 60))
    cmd = [sys.executable, str(script_path)]

    result = subprocess.run(
        cmd,
        cwd=str(APP_DIR),
        capture_output=True,
        text=True,
        timeout=timeout_seconds,
        check=False,
    )
    return result.returncode, result.stdout, result.stderr


def require_password_if_configured() -> None:
    password = get_secret_or_env("APP_PASSWORD", None)
    if not password:
        return

    if st.session_state.get("authenticated"):
        return

    st.title("Marex Solutions - Stock Screener")
    st.caption("Access protected")
    entered = st.text_input("Password", type="password")
    if st.button("Log in"):
        if entered == str(password):
            st.session_state["authenticated"] = True
            st.rerun()
        else:
            st.error("Invalid password")
    st.stop()


# -----------------------------------------------------------------------------
# Rendering helpers
# -----------------------------------------------------------------------------

def inject_css() -> None:
    st.markdown(
        f"""
        <style>
            :root {{
                --marex-blue-darkest: {MAREX_BLUE_DARKEST};
                --marex-blue-darker: {MAREX_BLUE_DARKER};
                --marex-blue-dark: {MAREX_BLUE_DARK};
                --marex-violet: {MAREX_SOLUTIONS_VIOLET};
                --marex-violet-darker: {MAREX_SOLUTIONS_VIOLET_DARKER};
                --marex-violet-50: {MAREX_SOLUTIONS_VIOLET_50};
                --marex-grey-light: {MAREX_GREY_LIGHT};
                --marex-grey-mid: {MAREX_GREY_MID};
                --marex-grey-mid-70: {MAREX_GREY_MID_70};
            }}
            html, body, [data-testid='stAppViewContainer'], .stApp {{
                background: {MAREX_BLUE_DARKEST} !important;
                color: {MAREX_GREY_LIGHT} !important;
            }}
            [data-testid='stHeader'] {{
                background: rgba(14, 13, 36, 0.96) !important;
                border-bottom: 1px solid {MAREX_BLUE_DARK};
            }}
            [data-testid='stToolbar'] {{
                color: {MAREX_GREY_LIGHT} !important;
            }}
            [data-testid='stSidebar'] {{
                background: {MAREX_BLUE_DARKER} !important;
                color: {MAREX_GREY_LIGHT} !important;
                border-right: 1px solid {MAREX_BLUE_DARK};
            }}
            .block-container {{
                /* Keep enough space below Streamlit's fixed top bar so the
                   Marex title is never clipped at the top of the page. */
                padding-top: 3.0rem !important;
                padding-bottom: 2rem !important;
                max-width: 100% !important;
            }}
            h1, h2, h3, h4, h5, h6, p, span, label, div {{
                color: {MAREX_GREY_LIGHT};
            }}
            .marex-header {{
                background: linear-gradient(135deg, {MAREX_BLUE_DARKER}, {MAREX_BLUE_DARK});
                border: 1px solid {MAREX_BLUE_DARK};
                border-radius: 18px;
                padding: 30px 24px 22px 24px;
                margin-top: 8px;
                margin-bottom: 12px;
                box-shadow: 0 18px 45px rgba(0, 0, 0, 0.24);
                overflow: visible !important;
            }}
            .marex-title {{
                display: block;
                overflow: visible !important;
                font-size: 30px;
                font-weight: 850;
                letter-spacing: 2px;
                color: #FFFFFF !important;
                line-height: 1.38;
                margin: 0 0 2px 0;
                padding-top: 4px;
            }}
            .marex-subtitle {{
                color: {MAREX_SOLUTIONS_VIOLET_50} !important;
                font-size: 14px;
                margin-top: 5px;
            }}
            .source-line {{
                display: flex;
                flex-wrap: wrap;
                gap: 8px;
                margin-top: 12px;
                align-items: center;
            }}
            .status-chip, .source-chip, .row-count-chip {{
                display: inline-flex;
                align-items: center;
                border-radius: 999px;
                padding: 6px 10px;
                font-size: 12px;
                font-weight: 700;
                letter-spacing: .2px;
            }}
            .status-chip {{
                background: {MAREX_GREEN};
                color: #FFFFFF !important;
                border: 1px solid {MAREX_GREEN};
            }}
            .source-chip, .row-count-chip {{
                background: {MAREX_BLUE_DARK};
                color: {MAREX_GREY_LIGHT} !important;
                border: 1px solid {MAREX_GREY_MID};
            }}
            .section-title {{
                color: #FFFFFF !important;
                font-size: 18px;
                font-weight: 800;
                margin: 2px 0 10px 0;
            }}
            .panel-card, .filters-card, .right-card {{
                background: {MAREX_BLUE_DARKER};
                border: 1px solid {MAREX_BLUE_DARK};
                border-radius: 16px;
                padding: 14px;
                box-shadow: 0 14px 35px rgba(0, 0, 0, 0.18);
            }}
            .filters-title-row, .panel-title-row {{
                display: flex;
                align-items: center;
                justify-content: space-between;
                gap: 12px;
                margin-bottom: 8px;
            }}
            .muted-text {{
                color: {MAREX_GREY_MID_70} !important;
                font-size: 13px;
            }}
            .stTextInput label, .stSelectbox label, .stFileUploader label {{
                color: {MAREX_GREY_LIGHT} !important;
                font-weight: 700 !important;
            }}
            .stTextInput input {{
                background: {MAREX_BLUE_DARK} !important;
                color: #FFFFFF !important;
                border: 1px solid {MAREX_GREY_MID} !important;
                border-radius: 9px !important;
            }}
            .stTextInput input::placeholder {{
                color: {MAREX_GREY_MID_70} !important;
                opacity: 1 !important;
            }}
            .stTextInput input:focus {{
                border-color: {MAREX_SOLUTIONS_VIOLET} !important;
                box-shadow: 0 0 0 1px {MAREX_SOLUTIONS_VIOLET} !important;
            }}
            div[data-baseweb='select'] > div {{
                background: {MAREX_BLUE_DARK} !important;
                color: #FFFFFF !important;
                border: 1px solid {MAREX_GREY_MID} !important;
                border-radius: 9px !important;
            }}
            div[data-baseweb='select'] > div * {{
                color: #FFFFFF !important;
                fill: #FFFFFF !important;
            }}
            /* Dropdown option list: light background + dark font for readability. */
            div[data-baseweb='popover'], div[data-baseweb='menu'], div[role='listbox'] {{
                background: {MAREX_GREY_LIGHT_30} !important;
                color: {MAREX_BLUE_DARKEST} !important;
                border: 1px solid {MAREX_SOLUTIONS_VIOLET_50} !important;
            }}
            div[data-baseweb='popover'] *, div[data-baseweb='menu'] *, div[role='listbox'] * {{
                color: {MAREX_BLUE_DARKEST} !important;
            }}
            div[role='option'], div[role='option'] * {{
                background: {MAREX_GREY_LIGHT_30} !important;
                color: {MAREX_BLUE_DARKEST} !important;
            }}
            div[role='option']:hover, div[role='option'][aria-selected='true'] {{
                background: {MAREX_SOLUTIONS_VIOLET_20} !important;
                color: {MAREX_BLUE_DARKEST} !important;
            }}
            .stButton > button, .stDownloadButton > button {{
                background: {MAREX_SOLUTIONS_VIOLET} !important;
                color: #FFFFFF !important;
                border: 1px solid {MAREX_SOLUTIONS_VIOLET} !important;
                border-radius: 10px !important;
                font-weight: 800 !important;
                min-height: 38px;
            }}
            .stButton > button:hover, .stDownloadButton > button:hover {{
                background: {MAREX_SOLUTIONS_VIOLET_50} !important;
                color: {MAREX_BLUE_DARKEST} !important;
                border-color: {MAREX_SOLUTIONS_VIOLET_50} !important;
            }}
            .stExpander {{
                background: {MAREX_BLUE_DARKER} !important;
                border: 1px solid {MAREX_BLUE_DARK} !important;
                border-radius: 12px !important;
            }}
            .right-card {{
                min-height: 650px;
            }}
            .detail-title {{
                color: #FFFFFF !important;
                font-size: 26px;
                font-weight: 850;
                line-height: 1.05;
                margin-bottom: 4px;
            }}
            .detail-subtitle {{
                color: {MAREX_SOLUTIONS_VIOLET_50} !important;
                font-size: 13px;
                margin-bottom: 12px;
            }}
            .detail-section-title {{
                color: #FFFFFF !important;
                font-size: 14px;
                font-weight: 800;
                margin: 14px 0 8px 0;
            }}
            .description-box {{
                background: {MAREX_BLUE_DARK};
                border: 1px solid {MAREX_GREY_MID};
                border-radius: 10px;
                padding: 12px;
                color: {MAREX_GREY_LIGHT} !important;
                max-height: 210px;
                overflow-y: auto;
                line-height: 1.45;
                margin-bottom: 12px;
            }}
            .detail-row {{
                display: grid;
                grid-template-columns: 165px 1fr;
                gap: 8px;
                padding: 7px 0;
                border-bottom: 1px solid rgba(80, 80, 104, 0.45);
            }}
            .detail-key {{
                color: {MAREX_GREY_MID_70} !important;
                font-weight: 700;
            }}
            .detail-value {{
                color: {MAREX_GREY_LIGHT} !important;
                word-break: break-word;
            }}
            .positive {{ color: {MAREX_GREEN} !important; font-weight: 800; }}
            .negative {{ color: {MAREX_CORAL} !important; font-weight: 800; }}
            .neutral {{ color: {MAREX_GREY_LIGHT} !important; }}

            /* Fallback styling for native Streamlit dataframe when AgGrid is not installed. */
            div[data-testid='stDataFrame'] {{
                background: {MAREX_BLUE_DARKER} !important;
                border: 1px solid {MAREX_BLUE_DARK} !important;
                border-radius: 12px !important;
                overflow: hidden !important;
            }}
            div[data-testid='stDataFrame'] * {{
                color: {MAREX_GREY_LIGHT} !important;
            }}
            [data-testid='stTabs'] button p {{
                color: {MAREX_GREY_LIGHT} !important;
                font-weight: 700 !important;
            }}
            [data-testid='stTabs'] button[aria-selected='true'] p {{
                color: #FFFFFF !important;
            }}
            [data-testid='stTabs'] [role='tablist'] {{
                gap: 4px;
                border-bottom: 1px solid {MAREX_BLUE_DARK};
            }}
            [data-testid='stTabs'] button[role='tab'] {{
                background: {MAREX_BLUE_DARK} !important;
                border-radius: 10px 10px 0 0 !important;
                padding: 8px 12px !important;
            }}
            [data-testid='stTabs'] button[aria-selected='true'] {{
                background: {MAREX_SOLUTIONS_VIOLET_DARKER} !important;
            }}
        </style>
        """,
        unsafe_allow_html=True,
    )


PERCENT_VALUE_FORMATTER = (
    JsCode("""
function(params) {
    if (params.value === null || params.value === undefined || params.value === '') {
        return '';
    }
    const value = Number(params.value);
    if (Number.isNaN(value)) {
        return '';
    }
    return value.toFixed(2) + '%';
}
""")
    if JsCode is not None
    else None
)

DETAIL_DOUBLE_CLICK_JS = (
    JsCode("""
function(event) {
    if (!event || !event.data || !event.node) {
        return;
    }

    const ticker = event.data.ticker || event.data.Ticker || '';
    const eventId = Date.now();

    // Store a one-shot double-click signal in hidden columns.
    // Checkbox selection alone does not update these fields, so Python can
    // distinguish a basket selection from an explicit request for details.
    event.node.setDataValue('_detail_event_id', eventId);
    event.node.setDataValue('_detail_ticker', ticker);
}
""")
    if JsCode is not None
    else None
)


AGGRID_CSS = {
    ".ag-root-wrapper": {
        "background-color": f"{MAREX_BLUE_DARKER} !important",
        "border": f"1px solid {MAREX_BLUE_DARK} !important",
        "border-radius": "12px !important",
        "overflow": "hidden !important",
    },
    ".ag-header": {
        "background-color": f"{MAREX_BLUE_DARK} !important",
        "color": "#FFFFFF !important",
        "border-bottom": f"1px solid {MAREX_GREY_MID} !important",
    },
    ".ag-header-cell": {
        "background-color": f"{MAREX_BLUE_DARK} !important",
        "color": "#FFFFFF !important",
        "font-weight": "800 !important",
        "border-right": f"1px solid {MAREX_GREY_MID} !important",
    },
    ".ag-header-cell-text": {"color": "#FFFFFF !important"},
    ".ag-row": {
        "background-color": f"{MAREX_BLUE_DARKER} !important",
        "color": f"{MAREX_GREY_LIGHT} !important",
        "border-bottom": f"1px solid {MAREX_BLUE_DARK} !important",
    },
    ".ag-row-odd": {"background-color": f"{MAREX_ROW_ALT} !important"},
    ".ag-cell": {
        "color": f"{MAREX_GREY_LIGHT} !important",
        "border-right": f"1px solid {MAREX_BLUE_DARK} !important",
    },
    ".ag-row-hover": {"background-color": f"{MAREX_SOLUTIONS_VIOLET_DARKEST} !important"},
    ".ag-row-selected": {
        "background-color": f"{MAREX_SOLUTIONS_VIOLET_DARKER} !important",
        "color": "#FFFFFF !important",
    },
    ".ag-row-selected .ag-cell": {"color": "#FFFFFF !important"},
    ".ag-paging-panel": {
        "background-color": f"{MAREX_BLUE_DARKER} !important",
        "color": f"{MAREX_GREY_LIGHT} !important",
        "border-top": f"1px solid {MAREX_BLUE_DARK} !important",
    },
    ".ag-icon": {"color": f"{MAREX_GREY_LIGHT} !important"},
}


def render_header(excel_path: Path, sheet_name: str, row_count: int) -> None:
    st.markdown(
        f"""
        <div class='marex-header'>
            <div class='marex-title'>MAREX SOLUTIONS</div>
            <div class='marex-subtitle'>Yahoo Finance Stock Screener - Web Dashboard</div>
            <div class='source-line'>
                <span class='status-chip'>Loaded</span>
                <span class='source-chip'>Source: {escape(excel_path)}</span>
                <span class='source-chip'>Sheet: {escape(sheet_name)}</span>
                <span class='source-chip'>{row_count:,} total rows</span>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_toolbar(uploaded_excel_key: str) -> Optional[Any]:
    toolbar_cols = st.columns([1.0, 1.35, 1.2, 3.0], gap="small")
    with toolbar_cols[0]:
        if st.button("Reload Excel", use_container_width=True):
            st.cache_data.clear()
            st.rerun()
    with toolbar_cols[1]:
        enable_refresh = to_bool(get_secret_or_env("ENABLE_REFRESH", False), default=False)
        if enable_refresh:
            if st.button("Refresh Yahoo Finance", use_container_width=True):
                refresh_password = get_secret_or_env("REFRESH_PASSWORD", None)
                entered_refresh_password = st.session_state.get("refresh_password", "")
                if refresh_password and entered_refresh_password != str(refresh_password):
                    st.error("Invalid refresh password")
                else:
                    with st.spinner("Running main.py. This can take several minutes..."):
                        try:
                            code, out, err = run_extraction_script()
                            st.cache_data.clear()
                            if code == 0:
                                st.success("Extraction completed. Data reloaded.")
                                if out:
                                    st.text_area("Extraction output", out, height=180)
                                st.rerun()
                            else:
                                st.error(f"Extraction failed with exit code {code}")
                                if out:
                                    st.text_area("stdout", out, height=160)
                                if err:
                                    st.text_area("stderr", err, height=160)
                        except subprocess.TimeoutExpired:
                            st.error("Extraction timeout reached.")
                        except Exception as exc:
                            st.error(f"Extraction error: {exc}")
        else:
            st.button("Refresh disabled", use_container_width=True, disabled=True)
    with toolbar_cols[2]:
        if to_bool(get_secret_or_env("ENABLE_REFRESH", False), default=False) and get_secret_or_env("REFRESH_PASSWORD", None):
            st.text_input("Refresh password", type="password", key="refresh_password", label_visibility="collapsed", placeholder="Refresh password")
    with toolbar_cols[3]:
        uploaded_excel = st.file_uploader(
            "Upload Excel for this session",
            type=["xlsx", "xlsm", "xls"],
            key=uploaded_excel_key,
            label_visibility="collapsed",
        )
    return uploaded_excel

def render_filters(df_raw: pd.DataFrame) -> dict[str, Any]:
    st.markdown(
        """
        <div class='filters-title-row'>
            <div class='section-title'>Filters</div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    top = st.columns([1.9, 1.25, 1.15, 1.0, 1.05, 1.55, 0.85], gap="small")
    with top[0]:
        search_text = st.text_input("Search", placeholder="Ticker, company, sector, country, universe...", key="filter_search")
    with top[1]:
        sector_values = []
        if "sector" in df_raw.columns:
            sector_values = sorted({normalize_text(x) for x in df_raw["sector"].dropna() if normalize_text(x)})
        ensure_multiselect_state("filter_sector", sector_values)
        sector_filter = st.multiselect("Sector", sector_values, key="filter_sector")
    with top[2]:
        country_values = []
        if "country" in df_raw.columns:
            country_values = sorted({normalize_text(x) for x in df_raw["country"].dropna() if normalize_text(x)})
        ensure_multiselect_state("filter_country", country_values)
        country_filter = st.multiselect("Country", country_values, key="filter_country")
    with top[3]:
        currency_values = []
        if "currency" in df_raw.columns:
            currency_values = sorted({normalize_text(x) for x in df_raw["currency"].dropna() if normalize_text(x)})
        ensure_multiselect_state("filter_currency", currency_values)
        currency_filter = st.multiselect("Currency", currency_values, key="filter_currency")
    with top[4]:
        universe_values = ["All"]
        if UNIVERSE_COLUMN in df_raw.columns:
            universe_values += collect_universe_options(df_raw[UNIVERSE_COLUMN])
        universe_index = 0
        if st.session_state.get("filter_universe") in universe_values:
            universe_index = universe_values.index(st.session_state.get("filter_universe"))
        universe_filter = st.selectbox("Universe", universe_values, index=universe_index, key="filter_universe")
    with top[5]:
        bucket_values = list(MARKET_CAP_BUCKETS.keys())
        bucket_index = 0
        if st.session_state.get("filter_market_cap_bucket") in bucket_values:
            bucket_index = bucket_values.index(st.session_state.get("filter_market_cap_bucket"))
        market_cap_bucket = st.selectbox("Market cap", bucket_values, index=bucket_index, key="filter_market_cap_bucket")
    with top[6]:
        st.write("")
        st.write("")
        st.button("Reset filters", on_click=reset_filters, use_container_width=True)

    c = st.columns(7, gap="small")
    vol_bucket_values = list(VOL_STRIKE_BUCKETS.keys())
    vol_bucket_index = 0
    if st.session_state.get("filter_var_vol_bucket") in vol_bucket_values:
        vol_bucket_index = vol_bucket_values.index(st.session_state.get("filter_var_vol_bucket"))
    var_vol_bucket = c[0].selectbox("Vol strike", vol_bucket_values, index=vol_bucket_index, key="filter_var_vol_bucket")
    pe_min = parse_float_input(c[1].text_input("P/E min", key="filter_pe_min"))
    pe_max = parse_float_input(c[2].text_input("P/E max", key="filter_pe_max"))
    ytd_min_pct = parse_float_input(c[3].text_input("YTD % min", key="filter_ytd_min"))
    ytd_max_pct = parse_float_input(c[4].text_input("YTD % max", key="filter_ytd_max"))
    one_week_min_pct = parse_float_input(c[5].text_input("1W % min", key="filter_1w_min"))
    one_week_max_pct = parse_float_input(c[6].text_input("1W % max", key="filter_1w_max"))

    return {
        "search_text": search_text,
        "sector_filter": sector_filter,
        "country_filter": country_filter,
        "currency_filter": currency_filter,
        "universe_filter": universe_filter,
        "market_cap_bucket": market_cap_bucket,
        "var_vol_bucket": var_vol_bucket,
        "pe_min": pe_min,
        "pe_max": pe_max,
        "ytd_min_pct": ytd_min_pct,
        "ytd_max_pct": ytd_max_pct,
        "one_week_min_pct": one_week_min_pct,
        "one_week_max_pct": one_week_max_pct,
    }



def render_detail_panel(row: Optional[pd.Series]) -> None:
    if row is None:
        st.markdown(
            """
            <div class='right-card'>
                <div class='detail-title'>No ticker selected</div>
                <div class='detail-subtitle'>Click a row in the table to display ticker details.</div>
            </div>
            """,
            unsafe_allow_html=True,
        )
        return

    ticker = normalize_text(row.get("ticker"))
    company = normalize_text(row.get("company_name"))
    sector = normalize_text(row.get("sector"))
    country = normalize_text(row.get("country"))
    currency = normalize_text(row.get("currency"))
    subtitle = " | ".join([x for x in [company, sector, country, currency] if x])
    description = normalize_text(row.get("company_description")) or "No description available."

    details_html: list[str] = [
        "<div class='right-card'>",
        f"<div class='detail-title'>{escape(ticker or 'Ticker')}</div>",
    ]
    if subtitle:
        details_html.append(f"<div class='detail-subtitle'>{escape(subtitle)}</div>")

    details_html.extend(
        [
            "<div class='detail-section-title'>Company description</div>",
            f"<div class='description-box'>{escape(description)}</div>",
            "<div class='detail-section-title'>Ticker details</div>",
        ]
    )

    for field in DETAIL_FIELDS:
        if field not in row.index:
            continue
        label = DISPLAY_NAMES.get(field, field)
        value = format_cell_value(field, row.get(field)) or "-"
        value_class = "detail-value"
        if field in {"YTD return", "1 week return"}:
            raw_val = safe_float(row.get(field))
            if raw_val is not None and raw_val > 0:
                value_class += " positive"
            elif raw_val is not None and raw_val < 0:
                value_class += " negative"
        details_html.append(
            "<div class='detail-row'>"
            f"<div class='detail-key'>{escape(label)}</div>"
            f"<div class='{value_class}'>{escape(value)}</div>"
            "</div>"
        )

    details_html.append("</div>")
    st.markdown("\n".join(details_html), unsafe_allow_html=True)


def render_chart(df: pd.DataFrame) -> None:
    st.markdown("<div class='section-title'>Top variance swap vol strike %</div>", unsafe_allow_html=True)
    if df.empty or "ticker" not in df.columns or "variance_swap_strike_vol_pct" not in df.columns:
        st.info("No chart data available.")
        return

    plot_df = df[["ticker", "variance_swap_strike_vol_pct"]].copy()
    plot_df["variance_swap_strike_vol_pct"] = pd.to_numeric(plot_df["variance_swap_strike_vol_pct"], errors="coerce")
    plot_df = plot_df.dropna().sort_values("variance_swap_strike_vol_pct", ascending=False).head(15)

    if plot_df.empty:
        st.info("No usable variance swap volatility data.")
        return

    fig = px.bar(
        plot_df.sort_values("variance_swap_strike_vol_pct", ascending=True),
        x="variance_swap_strike_vol_pct",
        y="ticker",
        orientation="h",
        labels={"variance_swap_strike_vol_pct": "Vol strike %", "ticker": "Ticker"},
        text="variance_swap_strike_vol_pct",
    )
    fig.update_traces(marker_color=MAREX_SOLUTIONS_VIOLET, texttemplate="%{text:.2f}%", textposition="outside")
    fig.update_layout(
        template="plotly_dark",
        paper_bgcolor=MAREX_BLUE_DARKER,
        plot_bgcolor=MAREX_BLUE_DARKEST,
        font_color=MAREX_GREY_LIGHT,
        height=430,
        margin=dict(l=10, r=10, t=20, b=10),
        xaxis=dict(gridcolor=MAREX_BLUE_DARK, zerolinecolor=MAREX_GREY_MID),
        yaxis=dict(gridcolor=MAREX_BLUE_DARK),
    )
    st.plotly_chart(fig, use_container_width=True)


@st.dialog("Ticker details", width="large")
def render_ticker_detail_dialog(row_data: dict[str, Any]) -> None:
    row = pd.Series(row_data)
    render_detail_panel(row)
    if st.button("Close", key="close_ticker_detail_dialog", use_container_width=True):
        st.rerun()


@st.dialog("Correlation matrix", width="large")
def render_correlation_matrix_dialog(corr_subset: pd.DataFrame, selected_tickers: list[str]) -> None:
    st.markdown("<div class='section-title'>Selected stocks correlation heatmap</div>", unsafe_allow_html=True)

    if corr_subset is None or corr_subset.empty:
        st.warning("No correlation data found for the selected tickers. Run main.py to generate the 'correlation matrix' sheet.")
        return

    fig = go.Figure(
        data=go.Heatmap(
            z=corr_subset.values,
            x=list(corr_subset.columns),
            y=list(corr_subset.index),
            zmin=-1,
            zmax=1,
            colorscale=[
                [0.0, "#B63A2B"],
                [0.5, "#FFB000"],
                [1.0, "#2D8D79"],
            ],
            colorbar=dict(title="Corr."),
            text=np.round(corr_subset.values, 2),
            texttemplate="%{text:.2f}",
            hovertemplate="%{y} / %{x}: %{z:.2f}<extra></extra>",
        )
    )
    fig.update_layout(
        template="plotly_dark",
        paper_bgcolor=MAREX_BLUE_DARKER,
        plot_bgcolor=MAREX_BLUE_DARKEST,
        font_color=MAREX_GREY_LIGHT,
        height=max(520, min(950, 42 * len(corr_subset) + 180)),
        margin=dict(l=80, r=20, t=20, b=80),
        xaxis=dict(side="bottom"),
        yaxis=dict(autorange="reversed"),
    )
    st.plotly_chart(fig, use_container_width=True)
    st.caption(f"{len(corr_subset)} ticker(s) loaded from sheet '{CORRELATION_SHEET}'.")

    csv_data = corr_subset.to_csv().encode("utf-8-sig")
    st.download_button(
        "Download selected correlation matrix as CSV",
        data=csv_data,
        file_name="selected_correlation_matrix.csv",
        mime="text/csv",
        use_container_width=True,
    )

    show_pairs = bool(st.session_state.get("corr_show_pairwise_table", False))
    toggle_label = "Hide pairwise correlation table" if show_pairs else "Show pairwise correlation table"
    if st.button(toggle_label, key="toggle_pairwise_correlation_table", use_container_width=True):
        show_pairs = not show_pairs
        st.session_state["corr_show_pairwise_table"] = show_pairs

    if show_pairs:
        st.markdown("<div class='section-title'>Pairwise correlations</div>", unsafe_allow_html=True)
        pairwise_df = build_pairwise_correlation_table(corr_subset)

        if pairwise_df.empty:
            st.info("No pairwise correlations available for the selected tickers.")
        else:
            st.dataframe(
                pairwise_df,
                hide_index=True,
                use_container_width=True,
                height=min(580, 42 + 34 * max(1, len(pairwise_df))),
                column_config={
                    "Ticker 1": st.column_config.TextColumn("Ticker 1"),
                    "Ticker 2": st.column_config.TextColumn("Ticker 2"),
                    "Correlation": st.column_config.NumberColumn("Correlation", format="%.4f"),
                },
            )

            pairwise_tsv = pairwise_df.to_csv(sep="\t", index=False, float_format="%.6f")
            pairwise_csv = pairwise_df.to_csv(index=False, float_format="%.6f").encode("utf-8-sig")

            render_copy_to_clipboard_button(pairwise_tsv)

            with st.expander("Manual copy fallback"):
                st.text_area(
                    "Copy this tab-separated table manually if your browser blocks clipboard access.",
                    value=pairwise_tsv,
                    height=150,
                    key="pairwise_correlation_manual_copy",
                )

            st.download_button(
                "Download pairwise correlations as CSV",
                data=pairwise_csv,
                file_name="selected_pairwise_correlations.csv",
                mime="text/csv",
                use_container_width=True,
            )

    if st.button("Close", key="close_correlation_dialog", use_container_width=True):
        st.session_state["show_correlation_dialog"] = False
        st.session_state["corr_show_pairwise_table"] = False
        st.rerun()


def _selected_rows_to_records(selected_rows: Any) -> list[dict[str, Any]]:
    if selected_rows is None:
        return []
    if isinstance(selected_rows, pd.DataFrame):
        return selected_rows.to_dict("records")
    if isinstance(selected_rows, list):
        return [row for row in selected_rows if isinstance(row, dict)]
    if isinstance(selected_rows, dict):
        return [selected_rows]
    return []


def build_aggrid_update_mode():
    """
    Keep checkbox selection updates and also listen to the hidden field update
    written by the row double-click JavaScript handler.
    """
    mode = GridUpdateMode.SELECTION_CHANGED
    for attr_name in ("VALUE_CHANGED", "MODEL_CHANGED"):
        try:
            mode = mode | getattr(GridUpdateMode, attr_name)
        except Exception:
            pass
    return mode


def get_detail_ticker_from_aggrid_response(response: dict[str, Any]) -> Optional[str]:
    """
    Return a ticker only when a real row double-click occurred.

    Checkbox selection changes and filter changes may rerun the app, but they do
    not write the hidden _detail_event_id field. This prevents ticker details
    from opening just because a checkbox was ticked.
    """
    if not response:
        return None

    records: list[dict[str, Any]] = []
    records.extend(_selected_rows_to_records(response.get("selected_rows")))
    records.extend(_selected_rows_to_records(response.get("data")))

    last_seen = safe_float(st.session_state.get("last_detail_event_id")) or 0.0
    best_event_id = last_seen
    best_ticker: Optional[str] = None

    for row in records:
        event_id = safe_float(row.get("_detail_event_id"))
        ticker = normalize_text(row.get("_detail_ticker")) or normalize_text(row.get("ticker"))
        if event_id is not None and event_id > best_event_id and ticker:
            best_event_id = event_id
            best_ticker = ticker

    if best_ticker is not None:
        st.session_state["last_detail_event_id"] = best_event_id

    return best_ticker


def get_selected_tickers_from_aggrid(selected_rows: Any) -> list[str]:
    records = _selected_rows_to_records(selected_rows)
    tickers = []
    seen = set()
    for row in records:
        ticker = normalize_text(row.get("ticker"))
        if ticker and ticker not in seen:
            tickers.append(ticker)
            seen.add(ticker)
    return tickers


def get_detail_row_from_selected_tickers(selected_tickers: list[str], filtered_df: pd.DataFrame) -> Optional[pd.Series]:
    # A single selected stock opens the ticker detail dialog. Multiple selected stocks
    # are interpreted as a correlation basket.
    if len(selected_tickers) != 1:
        return None
    return get_selected_row_by_ticker(selected_tickers[0], filtered_df)


def render_selectable_table(table_df: pd.DataFrame, filtered_df: pd.DataFrame) -> tuple[list[str], Optional[str]]:
    if table_df.empty:
        st.warning("No rows match the current filters.")
        return [], None

    selected_tickers: list[str] = []
    detail_ticker_to_open: Optional[str] = None

    if AGGRID_AVAILABLE:
        grid_df = table_df.copy()
        grid_df["_detail_event_id"] = 0
        grid_df["_detail_ticker"] = ""

        gb = GridOptionsBuilder.from_dataframe(grid_df)
        gb.configure_default_column(sortable=True, filter=True, resizable=True, min_column_width=92)
        gb.configure_selection("multiple", use_checkbox=True)
        gb.configure_grid_options(
            domLayout="normal",
            rowHeight=34,
            headerHeight=38,
            suppressRowHoverHighlight=False,
            animateRows=False,
            enableCellTextSelection=True,
            ensureDomOrder=True,
            rowMultiSelectWithClick=False,
            suppressRowClickSelection=True,
            onRowDoubleClicked=DETAIL_DOUBLE_CLICK_JS,
        )

        for col in grid_df.columns:
            if col in {"_detail_event_id", "_detail_ticker"}:
                gb.configure_column(col, hide=True, editable=True)
                continue

            header = DISPLAY_NAMES.get(col, col)
            width = 120
            if col == "ticker":
                width = 105
                gb.configure_column(col, header_name=header, pinned="left", width=width, checkboxSelection=True, headerCheckboxSelection=True)
            elif col == "company_name":
                width = 255
                gb.configure_column(col, header_name=header, width=width)
            elif col == "sector":
                width = 170
                gb.configure_column(col, header_name=header, width=width)
            elif col == "country":
                width = 135
                gb.configure_column(col, header_name=header, width=width)
            elif col in {"YTD return", "1 week return", "dividend_yield", "variance_swap_strike_vol", "variance_swap_strike_vol_pct", "variance_swap_strike_vol_pct_180d", "variance_swap_strike_vol_pct_360d"}:
                width = 125
                gb.configure_column(
                    col,
                    header_name=header,
                    width=width,
                    type=["numericColumn"],
                    valueFormatter=PERCENT_VALUE_FORMATTER,
                )
            elif col in NUMERIC_COLUMNS:
                width = 125
                gb.configure_column(col, header_name=header, width=width, type=["numericColumn"])
            else:
                gb.configure_column(col, header_name=header, width=width)

        response = AgGrid(
            grid_df,
            gridOptions=gb.build(),
            height=640,
            width="100%",
            data_return_mode=DataReturnMode.FILTERED_AND_SORTED,
            update_mode=build_aggrid_update_mode(),
            fit_columns_on_grid_load=False,
            theme="alpine",
            custom_css=AGGRID_CSS,
            allow_unsafe_jscode=True,
            key="marex_universe_aggrid",
        )
        selected_tickers = get_selected_tickers_from_aggrid(response.get("selected_rows"))
        detail_ticker_to_open = get_detail_ticker_from_aggrid_response(response)
    else:
        event = st.dataframe(
            table_df,
            hide_index=True,
            use_container_width=True,
            height=640,
            column_config=build_column_config(table_df),
            on_select="rerun",
            selection_mode="multi-row",
            key="marex_universe_table",
        )
        selected_rows = []
        try:
            selected_rows = list(event.selection.rows)
        except Exception:
            try:
                selected_rows = list(event.get("selection", {}).get("rows", []))
            except Exception:
                selected_rows = []
        for row_pos in selected_rows:
            if 0 <= row_pos < len(filtered_df):
                ticker = normalize_text(filtered_df.iloc[row_pos].get("ticker"))
                if ticker:
                    selected_tickers.append(ticker)

    return selected_tickers, detail_ticker_to_open


def load_correlation_matrix_for_current_source(
    uploaded_excel_state: Any,
    file_path_str: str,
    file_mtime_ns: int,
    file_size: int,
) -> pd.DataFrame:
    if uploaded_excel_state is not None:
        return read_uploaded_correlation_matrix(uploaded_excel_state)
    return read_correlation_matrix_excel(file_path_str, CORRELATION_SHEET, file_mtime_ns, file_size)


# -----------------------------------------------------------------------------
# Streamlit app
# -----------------------------------------------------------------------------

st.set_page_config(
    page_title="Marex Solutions - Stock Screener",
    page_icon="M",
    layout="wide",
    initial_sidebar_state="collapsed",
)

inject_css()
require_password_if_configured()

excel_path = get_excel_path()
sheet_name = get_sheet_name()
uploaded_excel_state = st.session_state.get("uploaded_excel")

file_path_str, file_mtime_ns, file_size = get_file_signature(excel_path)
try:
    if uploaded_excel_state is not None:
        try:
            uploaded_excel_state.seek(0)
        except Exception:
            pass
        raw_df = pd.read_excel(uploaded_excel_state, sheet_name=sheet_name)
        try:
            uploaded_excel_state.seek(0)
            params_df = pd.read_excel(uploaded_excel_state, sheet_name=DEFAULT_PARAM_SHEET)
            raw_df = merge_universe_from_params(raw_df, params_df)
        except Exception:
            pass
        df_raw = clean_dataframe(raw_df)
        data_source_label = Path(uploaded_excel_state.name)
    else:
        df_raw = read_dashboard_excel(file_path_str, sheet_name, file_mtime_ns, file_size)
        data_source_label = excel_path
except Exception as exc:
    render_header(excel_path, sheet_name, 0)
    st.error(f"Unable to load data: {exc}")
    st.stop()

render_header(data_source_label, sheet_name, len(df_raw))
render_toolbar("uploaded_excel")

filter_values = render_filters(df_raw)
filtered_df = filter_dataframe(
    df=df_raw,
    search_text=filter_values["search_text"],
    sectors=filter_values["sector_filter"],
    countries=filter_values["country_filter"],
    currencies=filter_values["currency_filter"],
    universe=filter_values["universe_filter"],
    market_cap_bucket=filter_values["market_cap_bucket"],
    var_vol_bucket=filter_values["var_vol_bucket"],
    pe_min=filter_values["pe_min"],
    pe_max=filter_values["pe_max"],
    ytd_min_pct=filter_values["ytd_min_pct"],
    ytd_max_pct=filter_values["ytd_max_pct"],
    one_week_min_pct=filter_values["one_week_min_pct"],
    one_week_max_pct=filter_values["one_week_max_pct"],
)

if "selected_ticker" not in st.session_state:
    st.session_state["selected_ticker"] = None
if "last_detail_event_id" not in st.session_state:
    st.session_state["last_detail_event_id"] = 0
# Correlation dialog is intentionally not persistent. It is opened only on an
# explicit click on the Load correlation matrix button.
if "corr_selected_tickers" not in st.session_state:
    st.session_state["corr_selected_tickers"] = []

st.markdown(
    f"""
    <div class='panel-title-row'>
        <div class='section-title'>Universe</div>
        <div class='muted-text'>Tick checkbox(es) to build a correlation basket. Double-click a row to open ticker details.</div>
    </div>
    """,
    unsafe_allow_html=True,
)

table_df = prepare_table_dataframe(filtered_df)
selected_tickers, detail_ticker_to_open = render_selectable_table(table_df, filtered_df)

st.markdown(
    f"<div class='muted-text'>{len(filtered_df):,} visible row(s) / {len(df_raw):,} total | {len(selected_tickers):,} selected</div>",
    unsafe_allow_html=True,
)

action_cols = st.columns([1.25, 1.25, 4.0], gap="small")
with action_cols[0]:
    load_corr_clicked = st.button(
        "Load correlation matrix",
        disabled=len(selected_tickers) < 2,
        use_container_width=True,
    )
with action_cols[1]:
    csv_df = prepare_table_dataframe(filtered_df)
    csv_data = csv_df.to_csv(index=False).encode("utf-8-sig")
    st.download_button(
        "Download CSV",
        data=csv_data,
        file_name="marex_stock_screener_view.csv",
        mime="text/csv",
        use_container_width=True,
    )

if load_corr_clicked:
    selected_for_corr = selected_tickers
    st.session_state["corr_selected_tickers"] = selected_for_corr
    st.session_state["corr_show_pairwise_table"] = False
    try:
        corr_matrix = load_correlation_matrix_for_current_source(
            uploaded_excel_state=uploaded_excel_state,
            file_path_str=file_path_str,
            file_mtime_ns=file_mtime_ns,
            file_size=file_size,
        )
        corr_subset = subset_correlation_matrix(corr_matrix, selected_for_corr)
        render_correlation_matrix_dialog(corr_subset, selected_for_corr)
    except Exception as exc:
        st.error(f"Unable to load correlation matrix: {exc}")

# Ticker details popup: opened only by an explicit row double-click.
if detail_ticker_to_open:
    detail_row = get_selected_row_by_ticker(detail_ticker_to_open, df_raw)
    if detail_row is not None:
        render_ticker_detail_dialog(detail_row.to_dict())
